### ISSUE TITLE
Redundant prefix nxos_ on all modules while already namespaced in nxos

### ISSUE THREAD

**Issue by bmillemathias** [ansible-collections/cisco.nxos#117]
##### SUMMARY
Now that the nxos collection exists it is useless to have a prefix nxos_ on all modules as we already name-spaced by the collection name. This is redundant and unnecessary long

##### ISSUE TYPE
- Bug Report

**Comment by NilashishC** [comment]
Hi @bmillemathias!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

Redirection using module short names have already been taken care of in runtime.yml and can be used in the following ways:
```
---
- hosts: nxos
  gather_facts: no
  collections:
    - cisco.nxos
  tasks:
    - user:
        name: test_user

- hosts: nxos
  gather_facts: no
  tasks:
    - cisco.nxos.user:
        name: test_user
```

If you face any issues with this, or if you have any further questions, please let us know by stopping by one of the two mailing lists, or IRC channel as appropriate:

- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
- #ansible-network on Freenode IRC

Thank you!
