### ISSUE TITLE
cisco.nxos.nxos_l2_interfaces trunk port issue

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.nxos#165]
##### SUMMARY
unable to configure trunk ports with cisco.nxos.nxos_l2_interfaces

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_l2_interfaces

##### ANSIBLE VERSION
ansible 2.9.13
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Dec  5 2019, 15:45:45) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE
```yaml
- name: Configure Trunk Ports
  cisco.nxos.nxos_l2_interfaces:
    config:
    - name: "{{ item.interface }}"
      mode: trunk
      trunk:
        native_vlan: "{{ item.native }}"
        allowed_vlans: "{{ item.allowed | default(omit) }}"
  with_items: 
    - "{{ trunk_ports }}"
  when: 
    - trunk_ports is defined
  tags:
    - nxos-interfaces
    - nxos-interfaces-trunks
```
trunk_ports:
  - { interface: Eth1/41, speed: "40000", allowed: "30,66,210,250", native: "300", port_type: layer2, lag: "104" }
  - { interface: Eth1/45, speed: "40000", allowed: "30,66,210,250", native: "300", port_type: layer2, lag: "104" }

##### ACTUAL RESULTS
The full traceback is:
Traceback (most recent call last):
  File "/home/feisa/.ansible/tmp/ansible-local-517372j0sj6xdg/ansible-tmp-1601307026.6933308-517379-144364860316432/AnsiballZ_nxos_l2_interfaces.py", line 102, in <module>
    _ansiballz_main()
  File "/home/feisa/.ansible/tmp/ansible-local-517372j0sj6xdg/ansible-tmp-1601307026.6933308-517379-144364860316432/AnsiballZ_nxos_l2_interfaces.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/feisa/.ansible/tmp/ansible-local-517372j0sj6xdg/ansible-tmp-1601307026.6933308-517379-144364860316432/AnsiballZ_nxos_l2_interfaces.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_l2_interfaces', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_cisco.nxos.nxos_l2_interfaces_payload_0k_iqyta/ansible_cisco.nxos.nxos_l2_interfaces_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_l2_interfaces.py", line 402, in <module>
  File "/tmp/ansible_cisco.nxos.nxos_l2_interfaces_payload_0k_iqyta/ansible_cisco.nxos.nxos_l2_interfaces_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_l2_interfaces.py", line 397, in main
  File "/tmp/ansible_cisco.nxos.nxos_l2_interfaces_payload_0k_iqyta/ansible_cisco.nxos.nxos_l2_interfaces_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/config/l2_interfaces/l2_interfaces.py", line 87, in execute_module
  File "/tmp/ansible_cisco.nxos.nxos_l2_interfaces_payload_0k_iqyta/ansible_cisco.nxos.nxos_l2_interfaces_payload.zip/ansible/module_utils/connection.py", line 185, in __rpc__
ansible.module_utils.connection.ConnectionError: switchport trunk allowed vlan 30,66,210,250
                                    ^
% Invalid command at '^' marker.
tc1-leafc004(config-if)# 
failed: [tc1-leafc004] (item={'interface': 'Eth1/45', 'speed': '40000', 'allowed': '30, 66, 210, 250', 'native': '300', 'port_type': 'layer2', 'lag': '104'}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "allowed": "30, 66, 210, 250",
        "interface": "Eth1/45",
        "lag": "104",
        "native": "300",
        "port_type": "layer2",
        "speed": "40000"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/feisa/.ansible/tmp/ansible-local-517372j0sj6xdg/ansible-tmp-1601307026.6933308-517379-144364860316432/AnsiballZ_nxos_l2_interfaces.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/feisa/.ansible/tmp/ansible-local-517372j0sj6xdg/ansible-tmp-1601307026.6933308-517379-144364860316432/AnsiballZ_nxos_l2_interfaces.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/feisa/.ansible/tmp/ansible-local-517372j0sj6xdg/ansible-tmp-1601307026.6933308-517379-144364860316432/AnsiballZ_nxos_l2_interfaces.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_l2_interfaces', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_cisco.nxos.nxos_l2_interfaces_payload_0k_iqyta/ansible_cisco.nxos.nxos_l2_interfaces_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_l2_interfaces.py\", line 402, in <module>\n  File \"/tmp/ansible_cisco.nxos.nxos_l2_interfaces_payload_0k_iqyta/ansible_cisco.nxos.nxos_l2_interfaces_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_l2_interfaces.py\", line 397, in main\n  File \"/tmp/ansible_cisco.nxos.nxos_l2_interfaces_payload_0k_iqyta/ansible_cisco.nxos.nxos_l2_interfaces_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/config/l2_interfaces/l2_interfaces.py\", line 87, in execute_module\n  File \"/tmp/ansible_cisco.nxos.nxos_l2_interfaces_payload_0k_iqyta/ansible_cisco.nxos.nxos_l2_interfaces_payload.zip/ansible/module_utils/connection.py\", line 185, in __rpc__\nansible.module_utils.connection.ConnectionError: switchport trunk allowed vlan 30,66,210,250\r\r\n                                    ^\r\n% Invalid command at '^' marker.\r\n\rtc1-leafc004(config-if)# \n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by NilashishC** [comment]
@feisa I'm not entirely sure what the issue is here. The module is attempting to send the following set of commands which seems to be correct. Maybe these two interfaces are not configured to be Layer 2 before the l2_interfaces task is run?
```
"commands": [
        "interface Ethernet1/41",
        "switchport mode trunk",
        "switchport trunk allowed vlan add 30,66,210,250",
        "switchport trunk native vlan 300"
    ],
```
```
"commands": [
        "interface Ethernet1/45",
        "switchport mode trunk",
        "switchport trunk allowed vlan 30,66,210,250",
        "switchport trunk native vlan 300"
    ],
```

**Comment by feisa** [comment]
I confirmed the interfaces are set to layer 2 trunk ports

**Comment by NilashishC** [comment]
@feisa If that's the case, are you expecting a different set of commands to be sent? What is the expected result here?

**Comment by feisa** [comment]
I expect the port configuration to be pushed correctly. Below are the interfaces config

interface Ethernet1/41
  description tc1-spinc001 ethernet1/51
  switchport mode trunk
  switchport trunk native vlan 300
  speed 40000
  channel-group 103 mode active

tc1-leafc003# sh run int e1/45

!Command: show running-config interface Ethernet1/45
!Running configuration last done at: Mon Sep 28 10:59:56 2020
!Time: Mon Sep 28 11:40:16 2020

version 9.3(3) Bios:version 5.3.1 

interface Ethernet1/45
  description tc1-spinc002 ethernet1/51
  switchport mode trunk
  switchport trunk native vlan 300
  speed 40000
  channel-group 103 mode active

**Comment by NilashishC** [comment]
@feisa I tried to reproduce the issue using this exact interface base config but it worked just fine. The module seems to be sending the correct commands. Can you please share what commands are you expecting?

**Comment by feisa** [comment]
I found the issue, we cant control interfaces that are part of a port channel, can we add a check for this?

**Comment by NilashishC** [comment]
We avoid handling edge cases like this is within the module code for a variety of reasons. However, you can leverage the facts returned by lag_interfaces module to get past this. Using the following tasks, you can build a list of interfaces that are part of a Port-Channel and then run the l2_interfaces task only against those interfaces that are not in that list:
```yaml
- cisco.nxos.lag_interfaces:
    state: gathered
  register: lag_intf
  
- ansible.builtin.set_fact:
    lag_members: "{{ lag_members|d([]) + [item.1.member] }}"
  loop: "{{ query('subelements', lag_intf['gathered'], 'members', {'skip_missing': True}) }}"

- name: Configure Trunk Ports
  cisco.nxos.l2_interfaces:
    config:
    - name: "{{ item.interface }}"
      mode: trunk
      trunk:
        native_vlan: "{{ item.native }}"
        allowed_vlans: "{{ item.allowed | default(omit) }}"
  with_items: "{{ trunk_ports }}"
  when: item.interface not in lag_members
```

As such, I'll be closing this ticket. If you have further questions on this, please feel free to reach out to us through #ansible-network or the [ansible-project](https://groups.google.com/forum/#!forum/ansible-project) mailing list.

Thank you!
