### ISSUE TITLE
cisco.nxos.nxos_l2_interfaces fails when unrelated interface is mode fex-fabric

### ISSUE THREAD

**Issue by FrankPetrilli** [ansible-collections/cisco.nxos#166]
##### SUMMARY

cisco.nxos.nxos_l2_interfaces only allowed for all switchport modes to be one of ["access", "trunk"]. Even an interface configured as fex-fabric unrelated to the playbook at hand will break playbook execution.

https://github.com/ansible-collections/cisco.nxos/blob/758d218fe6855a746ccad742869d65c7438c8fe9/plugins/module_utils/network/nxos/argspec/l2_interfaces/l2_interfaces.py#L48

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_l2_interfaces

##### ANSIBLE VERSION

```
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
Nexus 5010 version 5.2(1)N1(8b)

##### STEPS TO REPRODUCE

Existing state:
I have a Nexus switch with interfaces in trunk, access, and fex-fabric modes. Ethernet1/3 is mode trunk, Ethernet1/4 is mode trunk, Ethernet1/19 is mode fex-fabric.

```
interface Ethernet1/3
  switchport mode trunk
  switchport trunk native vlan 3000
  switchport trunk allowed vlan 1667,3000
interface Ethernet1/4
  switchport mode trunk
  switchport trunk native vlan 3000
  switchport trunk allowed vlan 1667,3000,3100-3101
interface Ethernet1/19
  switchport mode fex-fabric
  fex associate 100

```

Playbook:
Set Ethernet1/3 and Ethernet1/4's trunk allowed_vlans as follows:
```yaml
interfaces_downstream:
  - Ethernet1/3:
      description: "Ethernet1/3"
      native_vlan: 3000
      allowed_vlans: 1667,3000
  - Ethernet1/4:
      description: "Ethernet1/4"
      native_vlan: 3000
      allowed_vlans: 1667,3000,3100,3101
```
```yaml
    - name: "Configure switchport"
      with_dict: "{{ interfaces_downstream }}"
      cisco.nxos.nxos_l2_interfaces:
        state: replaced
        config:
          - name: "{{ item.key }}"
            mode: trunk
            trunk:
              native_vlan: "{{ item.value.native_vlan }}"
              allowed_vlans: "{{ item.value.allowed_vlans }}"
```

##### EXPECTED RESULTS

Successful replacement of interface allowed_vlans and native_vlan. Having full support for FEX would be nice as well.

##### ACTUAL RESULTS

```
failed: [switch-name] (item={u'key': u'Ethernet1/3', u'value': {u'native_vlan': 3000, u'allowed_vlans': u'1667,3000', u'description': u'Ethernet1/3'}}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "Ethernet1/3", "value": {"allowed_vlans": "1667,3000", "description": "Ethernet1/3", "native_vlan": 3000}}, "msg": "value of mode must be one of: access, trunk, got: fex-fabric found in config"}

```
