### ISSUE TITLE
PVLAN support on nxos_vlans

### ISSUE THREAD

**Issue by clammers** [ansible-collections/cisco.nxos#180]
##### SUMMARY

Support pVLAN configuration for nxos_vlans module. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nxos_vlans

##### ADDITIONAL INFORMATION

pVLANs are a state of the art layer2 isolation which was introduced by cisco long time ago.

```yaml
  cisco.nxos.nxos_vlans:
    config:
    - vlan_id: 5
      name: primary-test-vlan
      enabled: true
      pvlan_type: primary
      pvlan_associations: '10,11'
    - vlan_id: 10
      name: isolated-test-vlan
      enabled: true
      pvlan_type: isolated
    - vlan_id: 11
      name: community-test-vlan
      enabled: true
      pvlan_type: community
```
