### ISSUE TITLE
PVLAN support on nxos_interfaces

### ISSUE THREAD

**Issue by clammers** [ansible-collections/cisco.nxos#181]
##### SUMMARY

Support pVLAN configuration on nxos_interfaces
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nxos_interfaces
##### ADDITIONAL INFORMATION

```yaml
cisco.nxos.nxos_interfaces:
  config:
  - name: Vlan5
    description: pVLAN SVI
    enabled: true
    private_vlan_mapping: '10,11'
```
