### ISSUE TITLE
nxos_vpc Enhancements

### ISSUE THREAD

**Issue by clammers** [ansible-collections/cisco.nxos#183]
##### SUMMARY

For EVPN Fabrics using vPC Fabric Peering please support virtual peer-link configuration, Peer Switch and also ARP(v4) and ND(v6) synchronisation.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nxos_vpc
##### ADDITIONAL INFORMATION

```yaml
cisco.nxos.nxos_vpc:
  domain: 100
  role_priority: 1000
  system_priority: 2000
  pkl_dest: 192.168.100.4
  pkl_src: 10.1.100.20
  peer_gw: true
  auto_recovery: true         
  peer_switch: true
  vpl_dst: 192.168.100.4
  vpl_src: 10.1.100.20
  ip_arp_synchronize: true
  ipv6_nd_synchronize: true
```
