### ISSUE TITLE
Module cisco.nxos.nxos_vsan passes unsupported 'provider' parameter

### ISSUE THREAD

**Issue by jweigand** [ansible-collections/cisco.nxos#236]
##### SUMMARY
When attempting to use the cisco.nxos.nxos_vsan module, it is inserting a 'provider' parameter to the module, causing an error: "Unsupported parameters for (cisco.nxos.nxos_vsan) module: provider Supported parameters include: vsan"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.nxos.nxos_vsan

##### ANSIBLE VERSION

```paste below
ansible 2.9.14
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr  2 2020, 13:16:51) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### CONFIGURATION

```paste below
INVENTORY_CACHE_ENABLED(/etc/ansible/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
INVENTORY_ENABLED(/etc/ansible/ansible.cfg) = [u'auto', u'script', u'ini', u'toml', u'host_list', u'virtualbox', u'yaml', u'constructed', u'ldap_inventory']
```

##### OS / ENVIRONMENT

Cisco MDS 9148T

##### STEPS TO REPRODUCE

```yaml
  tasks:  
  - name: Create VSAN
    cisco.nxos.nxos_vsan:
      vsan:
      - id: 514
        interface:
        - fc1/1
        - fc1/2
        name: vsan-SAN-A
        remove: false
        suspend: false
```

##### EXPECTED RESULTS

Playbook runs, connects to switch and configures VSAN.

##### ACTUAL RESULTS

Playbook fails due to a 'provider' parameter being inserted (assuming some kind of default) that is not actually in the playbook code.

```paste below
{
    "_ansible_no_log": false,
    "invocation": {
        "module_args": {
            "vsan": [
                {
                    "interface": [
                        "fc1/1",
                        "fc1/2"
                    ],
                    "suspend": false,
                    "id": 514,
                    "remove": false,
                    "name": "vsan-SAN-A"
                }
            ],
            "provider": {
                "username": null,
                "authorize": false,
                "ssh_keyfile": null,
                "use_proxy": true,
                "auth_pass": null,
                "host": null,
                "timeout": null,
                "use_ssl": null,
                "password": null,
                "validate_certs": null,
                "port": null,
                "transport": "cli"
            }
        }
    },
    "changed": false,
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "msg": "Unsupported parameters for (cisco.nxos.nxos_vsan) module: provider Supported parameters include: vsan"
}
```

**Comment by NilashishC** [comment]
@jweigand Can you confirm if you're using `ansible_connection: ansible.netcommon.network_cli` for the target device? This should only happen if connection local is used.

cc @srbharadwaj

**Comment by srbharadwaj** [comment]
It should be same for all nxos modules .... adding Mike to confirm @mikewiebe

**Comment by NilashishC** [comment]
@srbharadwaj This is not an issue with older nxos modules that work with `connection: local`.

**Comment by jweigand** [comment]
@NilashishC Yes, I have `connection: network_cli` specified (and in my playbook run it'll show `using connection plugin network_cli (was local)`), still gets the error.

**Comment by NilashishC** [comment]
@jweigand `using connection plugin network_cli (was local)` will only show up if `connection: local` is somehow getting picked up. Here's the code snippet that does this redirection for your reference: https://github.com/ansible/ansible/blob/stable-2.9/lib/ansible/plugins/action/nxos.py#L84-L104.

To confirm, can you try overriding the connection to `network_cli` in the task itself, like the following:

```yaml
---
- hosts: nxos
  gather_facts: no
  tasks:
    - name: Create VSAN
      cisco.nxos.nxos_vsan:
        vsan:
        - id: 514
          interface:
          - fc1/1
          - fc1/2
          name: vsan-SAN-A
          remove: false
          suspend: false
      vars:
        ansible_connection: ansible.netcommon.network_cli
```

Thanks!
