### ISSUE TITLE
nxos_config parents paramter not working correctly when list provided

### ISSUE THREAD

**Issue by Brcinko** [ansible-collections/cisco.nxos#247]
**SUMMARY**

The _parents_ paramtere in _nxos_config_ can be provided with list of items. However, execution of config line (`lines` param) is done **only under last** item specified in _parents_ list.

From my point of view a config lines should be executed under each item provided in parents list.

**ISSUE TYPE**

- Bug Report

**COMPONENT NAME**

nxos_config

**ANSIBLE VERSION**

`ansible 2.10.5`

**CONFIGURATION**

```
forks           = 15
host_key_checking = False
connect_timeout = 300
command_timeout = 300
```

**OS / ENVIRONMENT**

Ubuntu 18.04.5 LTS
Nexus 5596 Chassis
NXOS ver.: 7.3(0)N1(1)

**STEPS TO REPRODUCE**

```
- name: Remove VLAN from Ethernet1/1-2
  cisco.nxos.nxos_config:
          lines:
                  - switchport trunk allowed vlan remove 161
          parents:
                  - interface Ethernet1/1
                  - interface Ethernet1/2
          save_when: modified
```

**EXPECTED RESULTS**

commands issued:

```
interface Ethernet1/1
 switchport trunk allowed vlan remove 161
interface Ethernet1/2
 switchport trunk allowed vlan remove 161
```

**ACTUAL RESULTS**

Specified command is executed only under last item in parents list

```
    "commands": [
        "interface Ethernet1/1",
        "interface Ethernet1/2",
        "switchport trunk allowed vlan remove 161"
    ]
```

**Comment by NilashishC** [comment]
@Brcinko the `parents` key was made a list to handle nested contexts such as the follows:
```yaml
- cisco.nxos.nxos_config:
    lines:
    - wait-igp-convergence
    - default-information originate
    parents:
    - router_bgp 65563
    - address-family ipv4 unicast
```

For the scenario that you mentioned you can try out something like:
```yaml
- name: Remove VLAN from Ethernet1/1-2
  cisco.nxos.nxos_config:
    lines:
    - switchport trunk allowed vlan remove 161
    parents:
    - "{{ intf }}"
    save_when: modified
  with_items:
  - interface Ethernet1/1
  - interface Ethernet1/2
  loop_control:
     loop_var: intf
```

As such, we will be closing this ticket. In case you wish to discuss this further please feel free to reach out to us either through the #ansible-network Freenode IRC channel or through the [ansible-project](https://groups.google.com/g/ansible-project) mailing list. Thank you for your interest in Ansible!
