### ISSUE TITLE
cisco.nxos.nxos_lag_interfaces dont create port-channel

### ISSUE THREAD

**Issue by urskog84** [ansible-collections/cisco.nxos#258]
no config line` interface port-channel 10 `is sent on task

```
ansible --version
ansible 2.10.5
```
```
- name: Configure Lag Trunks
  cisco.nxos.nxos_lag_interfaces:
    config: 
    - name: port-channel10
      members:
      - member: Ethernet1/40
        mode: active
      - member: Ethernet1/41
        mode: active
    state: overridden
````

Playbook results
````
changed: [sw-nxos] => {
    "after": [],
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "before": [],
    "changed": true,
    "commands": [
        "interface Ethernet1/40",
        "channel-group  10 mode active",
        "interface Ethernet1/41",
        "channel-group  10 mode active"
    ],
    "invocation": {
        "module_args": {
            "config": [
                {
                    "members": [
                        {
                            "member": "Ethernet1/40",
                            "mode": "active"
                        },
                        {
                            "member": "Ethernet1/41",
                            "mode": "active"
                        }
                    ],
                    "name": "port-channel 10"
                }
            ],
            "running_config": null,
            "state": "overridden"
        }
    }
}
````

**Comment by NilashishC** [comment]
@urskog84 Hi!

Thanks very much for your submission to Ansible. It sincerely means a lot to us.

If the port-channel itself does not exist in running-config, the `nxos_interfaces` module needs to be used to add it first and then add/update its members through the `nxos_lag_interfaces` modules. This behaviour is consistent across lag_interfaces resource modules for all platforms. 

A quick example:

```yaml
- name: Add port-channel10 interface
  cisco.nxos.nxos_interfaces:
    config:
    - name: port-channel10

- name: Configure Lag Trunks
  cisco.nxos.nxos_lag_interfaces:
    config: 
    - name: port-channel10
      members:
      - member: Ethernet1/40
        mode: active
      - member: Ethernet1/41
        mode: active
    state: overridden
```

As such, we're going to close this ticket. However, we're open to being corrected, should you wish to discuss. You can stop by one of our two mailing lists or IRC channel to talk about this and we might be persuaded otherwise.

- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code
- #ansible-network on Freenode IRC
Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
