### ISSUE TITLE
Nxos User Module Issue 

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.nxos#265]
##### SUMMARY
The following module fails nxos_snmp_user
```yaml
- name: Configure Admin User
  nxos_snmp_user:
    user: admin
    group: "{{ item.context }}"
    authentication: "{{ item.authentication }}"
    encrypt: "{{ item.encrypt }}" 
    privacy: "{{ localpassword }}"
    pwd: "{{ localpassword }}"
    state: present
  changed_when: false
  with_items: 
    - "{{ snmp_user }}"
  no_log: false
  tags:
    - nxos-snmp 
```
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_snmp_user

##### ANSIBLE VERSION
ansible 2.10.4
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /home/feisa/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### CONFIGURATION
COLLECTIONS_PATHS(/home/feisa/ansible-network/ansible.cfg) = ['/home/feisa/ansible-network/collections']
DEFAULT_ACTION_PLUGIN_PATH(/home/feisa/ansible-network/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ara/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/feisa/ansible-network/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ara/plugins/callback']
DEFAULT_FORKS(/home/feisa/ansible-network/ansible.cfg) = 100
DEFAULT_HOST_LIST(/home/feisa/ansible-network/ansible.cfg) = ['/home/feisa/ansible-network/inventories']
DEFAULT_MODULE_PATH(/home/feisa/ansible-network/ansible.cfg) = ['/home/feisa/ansible-network/library']
DEFAULT_ROLES_PATH(/home/feisa/ansible-network/ansible.cfg) = ['/home/feisa/ansible-network/roles']
DEFAULT_SCP_IF_SSH(/home/feisa/ansible-network/ansible.cfg) = True
GALAXY_SERVER_LIST(/home/feisa/ansible-network/ansible.cfg) = ['automation_hub', 'release_galaxy']
HOST_KEY_CHECKING(/home/feisa/ansible-network/ansible.cfg) = False
INTERPRETER_PYTHON(/home/feisa/ansible-network/ansible.cfg) = auto
PERSISTENT_COMMAND_TIMEOUT(/home/feisa/ansible-network/ansible.cfg) = 60000000
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/feisa/ansible-network/ansible.cfg) = 100
PERSISTENT_CONNECT_TIMEOUT(/home/feisa/ansible-network/ansible.cfg) = 6000

##### OS / ENVIRONMENT
 bootflash:///m9100-s5ek9-mz.8.4.1.bin

##### STEPS TO REPRODUCE
- name: Configure Admin User
  nxos_snmp_user:
    user: admin
    group: "{{ item.context }}"
    authentication: "{{ item.authentication }}"
    encrypt: "{{ item.encrypt }}" 
    privacy: "{{ localpassword }}"
    pwd: "{{ localpassword }}"
    state: present
  changed_when: false
  with_items: 
    - "{{ snmp_user }}"
  no_log: false
  tags:
    - nxos-snmp 

##### EXPECTED RESULTS
n/a

##### ACTUAL RESULTS
<ch1-sanmc002> EXEC /bin/sh -c 'rm -f -r /home/feisa/.ansible/tmp/ansible-local-572722u50rgiuu/ansible-tmp-1615824076.4030516-572763-39996377363990/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/feisa/.ansible/tmp/ansible-local-572722u50rgiuu/ansible-tmp-1615824076.4030516-572763-39996377363990/AnsiballZ_nxos_snmp_user.py", line 102, in <module>
    _ansiballz_main()
  File "/home/feisa/.ansible/tmp/ansible-local-572722u50rgiuu/ansible-tmp-1615824076.4030516-572763-39996377363990/AnsiballZ_nxos_snmp_user.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/feisa/.ansible/tmp/ansible-local-572722u50rgiuu/ansible-tmp-1615824076.4030516-572763-39996377363990/AnsiballZ_nxos_snmp_user.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_snmp_user', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib64/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_nxos_snmp_user_payload_zlge2vqj/ansible_nxos_snmp_user_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_snmp_user.py", line 413, in <module>
  File "/tmp/ansible_nxos_snmp_user_payload_zlge2vqj/ansible_nxos_snmp_user_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_snmp_user.py", line 338, in main
  File "/tmp/ansible_nxos_snmp_user_payload_zlge2vqj/ansible_nxos_snmp_user_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_snmp_user.py", line 131, in get_snmp_groups
TypeError: string indices must be integers
failed: [ch1-sanmc002] (item={'user': 'snmp', 'context': 'network-admin', 'authentication': 'sha', 'encrypt': True, 'hash': 894478857393806579493053137166121689798617008144}) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": {
        "authentication": "sha",
        "context": "network-admin",
        "encrypt": true,
        "hash": 894478857393806579493053137166121689798617008144,
        "user": "snmp"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/feisa/.ansible/tmp/ansible-local-572722u50rgiuu/ansible-tmp-1615824076.4030516-572763-39996377363990/AnsiballZ_nxos_snmp_user.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/feisa/.ansible/tmp/ansible-local-572722u50rgiuu/ansible-tmp-1615824076.4030516-572763-39996377363990/AnsiballZ_nxos_snmp_user.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/feisa/.ansible/tmp/ansible-local-572722u50rgiuu/ansible-tmp-1615824076.4030516-572763-39996377363990/AnsiballZ_nxos_snmp_user.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.cisco.nxos.plugins.modules.nxos_snmp_user', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python3.6/runpy.py\", line 205, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib64/python3.6/runpy.py\", line 96, in _run_module_code\n    mod_name, mod_spec, pkg_name, script_name)\n  File \"/usr/lib64/python3.6/runpy.py\", line 85, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_nxos_snmp_user_payload_zlge2vqj/ansible_nxos_snmp_user_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_snmp_user.py\", line 413, in <module>\n  File \"/tmp/ansible_nxos_snmp_user_payload_zlge2vqj/ansible_nxos_snmp_user_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_snmp_user.py\", line 338, in main\n  File \"/tmp/ansible_nxos_snmp_user_payload_zlge2vqj/ansible_nxos_snmp_user_payload.zip/ansible_collections/cisco/nxos/plugins/modules/nxos_snmp_user.py\", line 131, in get_snmp_groups\nTypeError: string indices must be integers\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

**Comment by NilashishC** [comment]
@feisa You have not shared the value of the variables you've used in the task. However, the following playbook worked fine for me.

```yaml
- hosts: nxos
  gather_facts: false
  vars:
    localpassword: testpassword_1
    snmp_user:
    - context: network-operator
      authentication: md5
      encrypt: True     
  tasks:
    - name: Configure Admin User
      cisco.nxos.nxos_snmp_user:
        user: admin
        group: "{{ item.context }}"
        authentication: "{{ item.authentication }}"
        encrypt: "{{ item.encrypt }}" 
        privacy: "{{ localpassword }}"
        pwd: "{{ localpassword }}"
        state: present
      changed_when: false
      with_items: 
        - "{{ snmp_user }}"
      no_log: false
      tags:
        - nxos-snmp
```

We would need the `snmp_user` list that the given task iterates through and the value of the `localpassword` variable to debug this further.

**Comment by feisa** [comment]
We used the following 

snmp_user:
  - { user: snmp, context: network-admin, authentication: sha, encrypt: yes, hash: 0x9cadd1b57db137ade7b342348ff2274aed30810 }
  - { user: admin, context: network-admin, authentication: sha, encrypt: yes, hash: 0x9cadd1b57db137ade7b23424242244aed30810 }
  
locapassword is a vaulted password of random 15 character alpha numeric

**Comment by feisa** [comment]
I have a slight work around on this so if we could prioritize my other issues that would be better

**Comment by NilashishC** [comment]
Even with the information you shared, I am unable to reproduce the traceback you're hitting with the following playbook:
```yaml
---
- hosts: nxos
  gather_facts: false
  vars:
    localpassword: M0L5pU#rhp8I9^2
    snmp_user:
      - { user: snmp, context: network-admin, authentication: sha, encrypt: yes, hash: 0x9cadd1b57db137ade7b342348ff2274aed30810 }
      - { user: admin, context: network-admin, authentication: sha, encrypt: yes, hash: 0x9cadd1b57db137ade7b23424242244aed30810 }    
  tasks:
    - name: Configure Admin User
      cisco.nxos.nxos_snmp_user:
        user: "{{ item.user }}"
        group: "{{ item.context }}"
        authentication: "{{ item.authentication }}"
        encrypt: "{{ item.encrypt }}" 
        privacy: "{{ localpassword }}"
        pwd: "{{ localpassword }}"
        state: present
      changed_when: false
      with_items: 
        - "{{ snmp_user }}"
      no_log: false
      tags:
        - nxos-snmp
 ```
 I am using ansible-base==2.10.4 and the latest cisco.nxos collection with Python 3.6 against a target running NX-OS 9.3.6.
