### ISSUE TITLE
Add available_network_resources key in nxos_facts module

### ISSUE THREAD

**Issue by trishnaguha** [ansible-collections/cisco.nxos#268]
- The key will return the list of all the RM resources available for the platform.
- This implementation doesn't affect the current functionality of the nxos_facts module and users can use the nxos_facts module in the same way as they were before.

Current behavior:
```
---
- name: Fatch facts
  hosts: nxos
  gather_facts: no
  collections:
    - cisco.nxos
  
  tasks:
    - name: Get basic facts 
      nxos_facts:
        gather_subset:
          - '!all'
```
output
```
ok: [10.8.8.73] => {
    "ansible_facts": {
        "ansible_net_api": "cliconf",
        "ansible_net_gather_network_resources": [],
        "ansible_net_gather_subset": [
            "default"
        ],
        "ansible_net_hostname": "an-nxos-01",
        "ansible_net_image": "bootflash:///titanium-d1.7.3.0.D1.1.bin",
        "ansible_net_license_hostid": "TB00090000B",
        "ansible_net_model": "NX-OSv Chassis (\"NX-OSv Supervisor Module\")",
        "ansible_net_platform": "N7K-C7018",
        "ansible_net_python_version": "3.9.2",
        "ansible_net_serialnum": "TM00090000B",
        "ansible_net_system": "nxos",
        "ansible_net_version": "7.3(0)D1(1)",
        "ansible_network_resources": {},
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "gather_network_resources": null,
            "gather_subset": [
                "!all"
            ],
            "provider": null
        }
    }
}
```
`After implementation of available_network_resources`
`Sample Playbook`:
```
---
- name: Get the list of  available resource Modules
  hosts: nxos
  gather_facts: no
  collections:
    - cisco.nxos
  
  tasks:
    - name: Get the list of available network resources for Cisco NX-OS and avoid fetching resource facts
      nxos_facts:
        gather_subset:
          - '!all'
        available_network_resources: true
```
Result: 
```
ok: [10.8.38.73] => {
    "ansible_facts": {
        "ansible_net_api": "cliconf",
        "ansible_net_gather_network_resources": [],
        "ansible_net_gather_subset": [
            "default"
        ],
        "ansible_net_hostname": "an-nxos-01",
        "ansible_net_image": "bootflash:///titanium-d1.7.3.0.D1.1.bin",
        "ansible_net_license_hostid": "TB00090000B",
        "ansible_net_model": "NX-OSv Chassis (\"NX-OSv Supervisor Module\")",
        "ansible_net_platform": "N7K-C7018",
        "ansible_net_python_version": "3.9.2",
        "ansible_net_serialnum": "TM00090000B",
        "ansible_net_system": "nxos",
        "ansible_net_version": "7.3(0)D1(1)",
        "ansible_network_resources": {},
        "available_network_resources": [
            "acl_interfaces",
            "acls",
            "bfd_interfaces",
            "bgp_address_family",
            "bgp_global",
            "bgp_neighbor_address_family",
            "hsrp_interfaces",
            "interfaces",
            "l2_interfaces",
            "l3_interfaces",
            "lacp",
            "lacp_interfaces",
            "lag_interfaces",
            "lldp_global",
            "lldp_interfaces",
            "ospf_interfaces",
            "ospfv2",
            "ospfv3",
            "static_routes",
            "telemetry",
            "vlans"
        ],
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "available_network_resources": true,
            "gather_network_resources": null,
            "gather_subset": [
                "!all"
            ],
            "provider": null
        }
    }
}
```
