### ISSUE TITLE
cisco.nxos.nxos_ospf_interfaces and "no ospfv3 passive interface" instruction

### ISSUE THREAD

**Issue by platu** [ansible-collections/cisco.nxos#269]
##### SUMMARY
The following playbook task does not lead to the `no ospfv3 passive interface` instruction in interface configuration. 
```
- name: SW3 INTERFACES
  hosts: sw3
  tasks:
    - cisco.nxos.nxos_ospf_interfaces:
        config:
        - name: "{{ item }}"
          address_family:
          - afi: ipv6
            processes:
            - process_id: "3"
              area:
                area_id: 0.0.0.0
            passive_interface: no
      with_items:
        - Vlan223
        - Vlan231
```
The result configuration is :
```
sw3# sh run int Vlan223

!Command: show running-config interface Vlan223
!Running configuration last done at: Tue Mar 23 20:53:07 2021
!Time: Tue Mar 23 21:06:06 2021

version 10.1(1) Bios:version

interface Vlan223
  no shutdown
  ipv6 address 2001:db8:df::/64 eui64
  ipv6 router ospfv3 3 area 0.0.0.0
```
##### ISSUE TYPE
- Bug Report
When applying the following OSPFv3 router daemon configuration with default passive interface policy, it is impossible to activate concerned interfaces individually.
```
- name: OSPFV3 PROCESS AND ROUTER_ID
  hosts: switches
  tasks:
    - set_fact:
        id_number: "{{ inventory_hostname | regex_replace('[^0-9]','') }}"
    - cisco.nxos.nxos_ospfv3:
        config:
          processes:
          - process_id: "{{ id_number }}"
            router_id: "0.0.0.{{ id_number }}"
            passive_interface:
              default: yes
```

##### COMPONENT NAME
cisco.nxos.nxos_ospf_interfaces 

##### ANSIBLE VERSION
```
ansible --version
ansible 2.9.9
  config file = /home/etu/labs/nx9300kv_ansible/ansible.cfg
  configured module search path = ['/home/etu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Jan 27 2021, 15:42:20) [GCC 10.2.0]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/etu/labs/nx9300kv_ansible/ansible.cfg) = ['/home/etu/labs/nx9300kv_ansible/hosts.yml']
DEPRECATION_WARNINGS(/home/etu/labs/nx9300kv_ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/etu/labs/nx9300kv_ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/etu/labs/nx9300kv_ansible/ansible.cfg) = 100
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/etu/labs/nx9300kv_ansible/ansible.cfg) = 100
PERSISTENT_CONNECT_TIMEOUT(/home/etu/labs/nx9300kv_ansible/ansible.cfg) = 100
RETRY_FILES_ENABLED(/home/etu/labs/nx9300kv_ansible/ansible.cfg) = False

```

##### OS / ENVIRONMENT
```
cat /etc/issue
Ubuntu 20.10
```

##### EXPECTED RESULTS
The `passive_interface` boolean choice should produce the `no ospfv3 passive interface` when set to *no*.

##### ACTUAL RESULTS
There is no instruction added to the interface confiugration.
