### ISSUE TITLE
cisco.nxos.nxos_bgp_address_family does not configure network statements 

### ISSUE THREAD

**Issue by feisa** [ansible-collections/cisco.nxos#285]
##### SUMMARY
The module does not configure network statements as expected 
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_bgp_address_family

##### ANSIBLE VERSION
ansible 2.10.4
  config file = /home/feisa/ansible-network/ansible.cfg
  configured module search path = ['/home/feisa/ansible-network/library']
  ansible python module location = /home/feisa/.local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Aug 18 2020, 08:33:21) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### CONFIGURATION
COLLECTIONS_PATHS(/home/feisa/ansible-network/ansible.cfg) = ['/home/feisa/ansible-network/collections']
DEFAULT_ACTION_PLUGIN_PATH(/home/feisa/ansible-network/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ara/plugins/action']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/feisa/ansible-network/ansible.cfg) = ['/usr/local/lib/python3.6/site-packages/ara/plugins/callback']
DEFAULT_FORKS(/home/feisa/ansible-network/ansible.cfg) = 100
DEFAULT_HOST_LIST(/home/feisa/ansible-network/ansible.cfg) = ['/home/feisa/ansible-network/inventories']
DEFAULT_MODULE_PATH(/home/feisa/ansible-network/ansible.cfg) = ['/home/feisa/ansible-network/library']
DEFAULT_ROLES_PATH(/home/feisa/ansible-network/ansible.cfg) = ['/home/feisa/ansible-network/roles']
DEFAULT_SCP_IF_SSH(/home/feisa/ansible-network/ansible.cfg) = True
GALAXY_SERVER_LIST(/home/feisa/ansible-network/ansible.cfg) = ['release_galaxy']
HOST_KEY_CHECKING(/home/feisa/ansible-network/ansible.cfg) = False
INTERPRETER_PYTHON(/home/feisa/ansible-network/ansible.cfg) = auto
PERSISTENT_COMMAND_TIMEOUT(/home/feisa/ansible-network/ansible.cfg) = 60000000
PERSISTENT_CONNECT_RETRY_TIMEOUT(/home/feisa/ansible-network/ansible.cfg) = 100
PERSISTENT_CONNECT_TIMEOUT(/home/feisa/ansible-network/ansible.cfg) = 6000

##### OS / ENVIRONMENT
nxos 9.3(6)

##### STEPS TO REPRODUCE
run the play book

- name: Configure BGP Address Family Settings
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: "{{ item.as_number | default('15047', true) }}"
      address_family:      
        - afi: ipv4
          safi: unicast
          networks:
            - prefix: "{{ item.route | default( omit ) }}" 
          distance:
            ebgp_routes: 20
            ibgp_routes: 100
            local_routes: 100
  with_items:
    - "{{ bgp_advertisement }}"
  tags:
    - nxos-bgp

bgp_advertisement: 
  - { route: '10.0.0.0/8' }
  - { route: '10.4.0.0/8' }

##### ACTUAL RESULTS
ok: [tc1-spinc002] => (item={'route': '10.0.0.0/8'}) => {
    "ansible_loop_var": "item",
    "before": {
        "address_family": [
            {
                "afi": "ipv4",
                "distance": {
                    "ebgp_routes": 20,
                    "ibgp_routes": 100,
                    "local_routes": 100
                },
                "safi": "unicast"
            }
        ],
        "as_number": "15047"
    },
    "changed": false,
    "commands": [],
    "invocation": {
        "module_args": {
            "config": {
                "address_family": [
                    {
                        "additional_paths": null,
                        "advertise_pip": null,
                        "advertise_system_mac": null,
                        "afi": "ipv4",
                        "aggregate_address": null,
                        "allow_vni_in_ethertag": null,
                        "client_to_client": null,
                        "dampen_igp_metric": null,
                        "dampening": null,
                        "default_information": null,
                        "default_metric": null,
                        "distance": {
                            "ebgp_routes": 20,
                            "ibgp_routes": 100,
                            "local_routes": 100
                        },
                        "export_gateway_ip": null,
                        "inject_map": null,
                        "maximum_paths": null,
                        "networks": [
                            {
                                "prefix": "10.0.0.0/8",
                                "route_map": null
                            }
                        ],
                        "nexthop": null,
                        "redistribute": null,
                        "retain": null,
                        "safi": "unicast",
                        "suppress_inactive": null,
                        "table_map": null,
                        "timers": null,
                        "vrf": null,
                        "wait_igp_convergence": null
                    }
                ],
                "as_number": "15047"
            },
            "running_config": null,
            "state": "merged"
        }
    },
    "item": {
        "route": "10.0.0.0/8"
    }
}

router bgp 15047
  router-id 10.4.255.2
  log-neighbor-changes
  address-family ipv4 unicast
    distance 20 100 100
  neighbor 10.4.255.1
    remote-as 15047
    description iBGP
    update-source loopback0
    address-family ipv4 unicast
      route-map FROM_INTERNAL in
      route-map TO_INTERNAL out
      soft-reconfiguration inbound always

**Comment by NilashishC** [comment]
@feisa The playbook isn't setting the `networks` key correctly. Could you please try the following instead and let us know if it works?

```yaml
- name: Configure BGP Address Family Settings
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: "{{ item.as_number | default('15047', true) }}"
      address_family:
        - afi: ipv4
          safi: unicast
          networks:
            - prefix: '10.0.0.0/8' 
            - prefix: '10.4.0.0/8'
          distance:
            ebgp_routes: 20
            ibgp_routes: 100
            local_routes: 100
```

**Comment by NilashishC** [comment]
@feisa in that case, can you share the existing BGP config on the box? Also, the Ansible version and the Python version you are on.

**Comment by feisa** [comment]
router bgp 15047
  router-id 10.4.255.1
  log-neighbor-changes
  address-family ipv4 unicast
  neighbor 10.4.255.2
    remote-as 15047
    description iBGP
    update-source loopback0
    address-family ipv4 unicast
      route-map FROM_INTERNAL in
      route-map TO_INTERNAL out
      next-hop-self
      soft-reconfiguration inbound always

**Comment by feisa** [comment]
Sorry for the delay on this, just catching up

**Comment by NilashishC** [comment]
@feisa I wasn't able to reproduce the issue even with the config you shared as base config. The initial playbook is incorrect and I can see why that would not send the correct commands, but the playbook I shared should have worked.

```
nxos-9k-936-psi# show version | grep NXOS:
 NXOS: version 9.3(6)

nxos-9k-936-psi# show running-config | section "^router bgp"
router bgp 15047
  router-id 10.4.255.1
  log-neighbor-changes
  address-family ipv4 unicast
  neighbor 10.4.255.2
    remote-as 15047
    description iBGP
    update-source loopback0
    address-family ipv4 unicast
      route-map FROM_INTERNAL in
      route-map TO_INTERNAL out
      next-hop-self
      soft-reconfiguration inbound always
```

```yaml
---
- hosts: nxos
  gather_facts: no
  tasks:
    - name: Configure BGP Address Family Settings
      cisco.nxos.nxos_bgp_address_family:
        config:
          as_number: "{{ item.as_number | default('15047', true) }}"
          address_family:
            - afi: ipv4
              safi: unicast
              networks:
                - prefix: "{{ bgp_advertisement[0].route }}"
                - prefix: "{{ bgp_advertisement[1].route }}"
              distance:
                ebgp_routes: 20
                ibgp_routes: 100
                local_routes: 100
      vars:
        bgp_advertisement:
          - {route: '10.0.0.0/8'}
          - {route: '10.4.0.0/8'}
```

Redacted task output
=================
```
 "commands": [
        "router bgp 15047",
        "address-family ipv4 unicast",
        "distance 20 100 100",
        "network 10.4.0.0/8",
        "network 10.0.0.0/8"
 ]
```

**Comment by NilashishC** [comment]
cc @praveenramoorthy

**Comment by feisa** [comment]
@NilashishC how do you handle an unknown amount of bgp networks? I have some BGP advertisements that have 10 networks to advertise vs  some devices with 2 or 3

**Comment by NilashishC** [comment]
A little tweak in your vars should make it work.

```yaml
---
- hosts: nxos
  gather_facts: no
  vars:
     bgp_advertisement:
       - {prefix: '10.0.0.0/8'}
       - {prefix: '10.4.0.0/8'}
  tasks:
    - name: Configure BGP Address Family Settings
      cisco.nxos.nxos_bgp_address_family:
        config:
          as_number: "{{ item.as_number | default('15047', true) }}"
          address_family:
            - afi: ipv4
              safi: unicast
              networks: "{{ bgp_advertisement }}"
              distance:
                ebgp_routes: 20
                ibgp_routes: 100
                local_routes: 100
```
