### ISSUE TITLE
Option to not save the output of specific commands

### ISSUE THREAD

**Issue by etiedem** [ansible-collections/cisco.nxos#286]
##### SUMMARY

Add the option to skip the process of adding to the results list

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

cisco.nxos.nxos_command

##### ADDITIONAL INFORMATION

On large runs where I have to run various setup commands to get the output and I only care about 1 in 4 commands it would be nice to only save the output from the 1 command

```yaml
    - name: Loop through VDC (nxos)
      cisco.nxos.nxos_command:
        commands:
          - command: "switchto vdc {{ item['vdc_name'] }}"
            output: none
          - command: "term len 0"
            output: none
          - command: "show interface status"
            output: json
          - command: "exit"
            output: none
      when: item['type'] != 'Admin'
      loop: "{{ vdc['parsed'] }}"
      register: result
```

**Comment by NilashishC** [comment]
@etiedem I am not sure if I understand the issue here. But if you want to see the output of just one command, you can simply do that by referencing the correct item in the `stdout_lines` list of the task output result. For example, if you want to see the output of "show interface status", which is the 3rd element in the `commands` list, you can use:

```yaml
- debug:
    msg: "{{ result["stdout_lines"][2] }}"
```

If you want this to be even more dynamic, you can use the `index_of` filter from the [ansible.utils](https://github.com/ansible-collections/ansible.utils/) collection and leverage it in the playbook:

```yaml
---
- hosts: nxos
  gather_facts: no
  vars:
    relevant_cmd: show version
    cmds:
      - command: show interfaces
      - command: show version
      - command: show inventory
  tasks:
    - cisco.nxos.nxos_command:
        commands: "{{ cmds }}"
      register: result
      
    - debug:
        msg: "{{ result['stdout_lines'][cmds|ansible.utils.index_of('eq', relevant_cmd, 'command')] }}"
```

As such, I'll be closing this issue. If you wish to discuss this further please reach out to us through the #ansible-network Freenode IRC channel or through the [ansible-project](https://groups.google.com/g/ansible-project) mailing list.

Please note that closed issues are not actively monitored for new comments.

Thank you!
