### ISSUE TITLE
bgp_neighbor_address_family -> add advertise l2vpn evpn

### ISSUE THREAD

**Issue by alexanderdeca** [ansible-collections/cisco.nxos#302]
##### SUMMARY
For automating vxlan deployments the **_bgp_neighbor_address_family_** is missing the _advertise l2vpn evpn_ command under BGP > vrf > ipv4 unicast as this is the case with the **_bgp_neighbor_af_**

bgp_neighbor_af example.

- name: VRFS under BGP process
  nxos_bgp_af:
    asn: "{{ asn }}"
    vrf: "{{ item.vrf }}"
    afi: "{{ item.afi }}"
    safi: "{{ item.safi }}"
    **advertise_l2vpn_evpn: "true"**
  loop: "{{ vrfs }}"

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

bgp_neighbor_address_family

##### ADDITIONAL INFORMATION

```
- name: VRFS under BGP process
  nxos_bgp_af:
    asn: "{{ asn }}"
    vrf: "{{ item.vrf }}"
    afi: "{{ item.afi }}"
    safi: "{{ item.safi }}"
    **advertise_l2vpn_evpn: "true"**
  loop: "{{ vrfs }}"
```
