### ISSUE TITLE
nxos_bgp_global - peer_type is never issued

### ISSUE THREAD

**Issue by allenrobel** [ansible-collections/cisco.nxos#308]
##### SUMMARY
When ``peer_type`` is set to ``fabric-external``, the corresponding CLI ``peer-type fabric-external`` is not issued.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_bgp_global

##### ANSIBLE VERSION

```
ansible [core 2.11.0b4] 
  config file = /Users/arobel/.ansible.cfg
  configured module search path = ['/Users/arobel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/arobel/ansible-latest/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/arobel/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/arobel/ansible-latest/bin/ansible
  python version = 3.9.0 (default, Oct 27 2020, 14:15:17) [Clang 12.0.0 (clang-1200.0.32.21)]
  jinja version = 2.11.3
  libyaml = True
```

##### CONFIGURATION

```
CACHE_PLUGIN_TIMEOUT(/Users/arobel/.ansible.cfg) = 86400
DEFAULT_LOG_PATH(/Users/arobel/.ansible.cfg) = /tmp/ansible.log
HOST_KEY_CHECKING(/Users/arobel/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

NXOS: 9.3(7)
Nexus9504 with N9K-SUP-B + N9K-X9732C-EX linecards

##### STEPS TO REPRODUCE

1. It doesn't matter if the BGP neighbor is present or not in the config.  Below, we start with the BGP neighbor removed from the config.
2. Run the task below.  We tried changing peer_type to ``fabric-border-leaf`` with the same results.  We also tried changing peer_type to ``asdf`` and the module returned the expected error.

```yaml
    -   cisco.nxos.nxos_bgp_global:
            config:
                as_number: '65001'
                neighbors:
                -   neighbor_address: 10.239.0.13
                    peer_type: fabric-external
                    remote_as: '65002'
            state: merged
        name: test peer_type
```

##### EXPECTED RESULTS

The following CLI should be issued:

```
router bgp 65001
   neighbor 10.239.0.13
      remote-as 65002
      peer-type fabric-external
```

##### ACTUAL RESULTS

See attached files:

debug_output.txt - contains the output of ansible-playbook -vvv, including the below commands list.

nxapi_server_log.txt - contains the output of 'show nxapi-server logs' after the playbook is run.

```
    "commands": [
        "router bgp 65001",
        "neighbor 10.239.0.13",
        "remote-as 65002"
    ],
```

Resulting neighbor config:

```
switch(config-router)# sh run bgp | sec 10.239.0.13
  neighbor 10.239.0.13
    remote-as 65002
```
[debug_output.txt](https://github.com/ansible-collections/cisco.nxos/files/6604678/debug_output.txt)
[nxapi_server_log.txt](https://github.com/ansible-collections/cisco.nxos/files/6604692/nxapi_server_log.txt)
