### ISSUE TITLE
nxos_feature: Add Missing Platform Features

### ISSUE THREAD

**Issue by timway** [ansible-collections/cisco.nxos#321]
##### SUMMARY

When trying to ensure a number of features were enabled I noticed several of them are missing from the module. They are valid features on a Nexus 7706 running 8.4(2). These are common features - is the assumption these are just validated with nxos_config?

- dhcp
- hsrp
- interface-vlan
- lacp
- lldp
- ospf
- pim
- vpc

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
nxos_feature

##### ADDITIONAL INFORMATION

```yaml
- cisco.nxos.nxos_feature:
    feature: "{{ feature }}"
    state: enabled
  loop:
    - dhcp
    - hsrp
    - interface-vlan
    - lacp
    - lldp
    - ospf
    - pim
    - vpc
  loop_control:
    loop_var: feature
```
