### ISSUE TITLE
nxos_logging: Not Able To Specify Remote Server Port Number

### ISSUE THREAD

**Issue by timway** [ansible-collections/cisco.nxos#322]
##### SUMMARY

Be able to specify a port number for a remote server destination.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nxos_logging

##### ADDITIONAL INFORMATION

In my experience it's fairly common for enterprises to run syslog collectors on non-standard ports. This is required to configure logging on devices in those environments.

```yaml
- cisco.nxos.nxos_logging:
    aggregate:
      - dest: server
        remote_server: 9.9.9.9
        facility: local4
        facility_level: 5
        use_vrf: default
        port: 9999
```
