### ISSUE TITLE
nxos_snmp_traps: Support Configuring Optional Keywords

### ISSUE THREAD

**Issue by timway** [ansible-collections/cisco.nxos#328]
##### SUMMARY

https://github.com/ansible-collections/cisco.nxos/blob/main/plugins/modules/nxos_snmp_traps.py#L219-L259

It is possible to enable optional keywords of certain types of SNMP traps. Two examples:

```
snmp-server enable traps snmp authentication
snmp-server enable traps link cisco-xcvr-mon-status-chg
```

vs (module supported below)

```
snmp-server enable traps snmp
snmp-server enable traps link
```

The module would fail to configure the "authentication" and "cisco-xcvr-mon-status-chg" optional keywords in the respective areas.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

This is for IOS but the same applies for NXOS (google is failing me to find the NXOS version): https://www.cisco.com/c/en/us/td/docs/ios-xml/ios/snmp/command/nm-snmp-cr-book/nm-snmp-cr-s3.html#wp2426083542

```yaml
- cisco.nxos.nxos_snmp_traps:
    group: snmp
    state: enabled
    optional:
      - authentication
- cisco.nxos.nxos_snmp_traps:
    group: link
    state: enabled
    optional:
      - cisco-xcvr-mon-status-chg
```
