### ISSUE TITLE
nxos_zone_zoneset want to recreate already existing zone member on Cisco MDS SAN Switch

### ISSUE THREAD

**Issue by albertdamien** [ansible-collections/cisco.nxos#339]
##### SUMMARY
Hello, when I try to add a member of a zone that already exists in the zone, it is recreated when it should not do anything

Here below, the ansible code that is used to make the test

```
tasks:
    - name: Test that zone/zoneset module works
      cisco.nxos.nxos_zone_zoneset:
        zone_zoneset_details:
        - mode: basic
          smart_zoning: true
          vsan: 100
          zone:
          - members:
            - devtype: initiator
              pwwn: 20:00:00:25:b5:10:a0:00
            name: SZ-WLD-IAAS1-HUABVA07
```
and here is below the return of the "show zone vsan 100" command on the test MDS switch. This one is in version 8.4(2a) !

```
C9148T-BVA07-0031-LAB1-01# sh zone
zone name SZ-WLD-IAAS1-HUABVA07 vsan 100
  pwwn 20:00:00:25:b5:10:a0:00 [P011W01ILBEX001-H0]  init
  pwwn 20:00:00:25:b5:10:a0:01 [P011W01ILBEX002-H0]  init
  pwwn 20:00:00:25:b5:10:a0:02 [P011W01ILBEX003-H0]  init
  pwwn 20:00:00:25:b5:10:a0:03 [P011W01ILBEX004-H0]  init
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
file cisco/nxos/plugins/modules/storage/nxos_zone_zoneset.py of cisco.nxos collection seems impacted

##### ANSIBLE VERSION

```
ansible 2.9.23
  config file = /home/osadmin/dalbert/ucs/ansible/ansible.cfg
  configured module search path = [u'/home/osadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 16 2020, 22:23:17) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

```

##### COLLECTION VERSION

```
   cisco-nxos-2.5.0
   ansible-netcommon-2.3.0
   ansible-utils-2.3.1
```

##### CONFIGURATION

```
TRANSFORM_INVALID_GROUP_CHARS(/home/osadmin/dalbert/ucs/ansible/ansible.cfg) = ignore

```

##### OS / ENVIRONMENT
```
OS: Centos 7.9 2009
NXOS Switch: MDS 9148T 48X32G FC (1 RU) Chassis
NXOS Version: 8.4(2a)
```

##### STEPS TO REPRODUCE
Launch the simple playbook in check/dry-run mode:

```
tasks:
    - name: Test that zone/zoneset module works
      cisco.nxos.nxos_zone_zoneset:
        zone_zoneset_details:
        - mode: basic
          smart_zoning: true
          vsan: 100
          zone:
          - members:
            - devtype: initiator
              pwwn: 20:00:00:25:b5:10:a0:00
            name: SZ-WLD-IAAS1-HUABVA07
```

```
TASK [debug] *********************************************************************************************************************************
ok: [C9148T-BVA07-0031-LAB1-01] => {
    "output": {
        "changed": false,
        "commands": [
            "terminal dont-ask",
            "zone name SZ-WLD-IAAS1-HUABVA07 vsan 100",
            "member pwwn 20:00:00:25:b5:10:a0:00 initiator",
            "no terminal dont-ask"
        ],
        "failed": false,
        "msg": "Check Mode: No cmds issued to the hosts"
    }
}

```

##### EXPECTED RESULTS
Since the zone member already exists in the zone, the module should exit in green without trying to make any changes to the switch

##### ACTUAL RESULTS
Instead of that, the module comes out in yellow after replaying the command to add a member of the zone

The problem seems to take place in the "nxos_zone_zoneset.py" file when calling the isZoneMemberPresent() method.

We are obviously trying to compare the presence of the line "pwwn 20:00:00:25:b5:10:a0:00 initiator" (the cmd var) inside the zone whose lines are formatted as follows: "pwwn 20:00:00:25:b5:10:a0:00 [P011W01ILBEX001-H0] initiator" (the eachline var)

Maybe the output format of the NXOS command "show zone" has changed between version 8.4(1) and the version I use, 8.4(2a) ?

Thanks

Regards,
Damien ALBERT
