### ISSUE TITLE
FCALIAS for Cisco MDS Switches

### ISSUE THREAD

**Issue by slemont68** [ansible-collections/cisco.nxos#340]
##### SUMMARY

We would love to have a module to create fcalias
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

create fcalias
##### ADDITIONAL INFORMATION

Our vendor setup our VxBlock and used fcalias on the switches.  It would be great to not have to change the configuration because that might affect our support.

```yaml

nxos_devicealias:
          distribute: yes
 - mode: enhanced
      vsan: 22
      zone:
        name: host123_to_storage123
    - device_alias: host123
    - pwwn: 10:11:11:11:11:11:11:11
    -  device_alias: storage123
    -  pwwn: 61:61:62:62:12:12:12:12
-fc_alias: host_to_storage vsan 22
-members:
   - pwwn: 10:11:11:11:11:11:11:11
   - pwwn: 61:61:62:62:12:12:12:12
  - zone commit vsan 22
zoneset:
   - action: activate
      members:
      - name:  host_to_storage
        name: production
```
