### ISSUE TITLE
nxos_ospfv2: No capability to remove VRFs from OSPF processes

### ISSUE THREAD

**Issue by tpeyton1** [ansible-collections/cisco.nxos#357]
##### SUMMARY
The new `nxos_ospfv2` module lacks the ability to remove VRFs from existing OSPF processes. The module `nxos_ospf_vrf` had this capability, but is deprecated citing that the `nxos_ospfv2` module replaces it. I haven't been able to use the new module to remove a VRF from an OSPF process without removing the entire process.

My current workaround is to use the `nxos_ospf_vrf` module for removing VRFs from OSPF processes, but I am concerned that once this module gets removed that there will no longer be an idempotent way to remove VRFs from OSPF processes.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nxos_ospfv2

##### ADDITIONAL INFORMATION

I believe the main issue is that the new `nxos_ospfv2` module is OSPF process-centric, so when using the `deleted` state, the module just removes everything up to and including the process despite me only wanting to remove the VRF related configuration. It would be great if there was an option to specify state absent/present at the VRF level. I may also just be using the new module incorrectly, in which case I apologize in advance.

I have included some example code below to show the behavior of both modules attempting to perform the same task of removing the 'example-vrf' VRF from the OSPF router with process ID 1.

Using `nxos_ospfv2`:
```yaml
# Before state:
# router ospf 1
#   vrf example-vrf

- name: Remove VRF from OSPF process
  cisco.nxos_ospfv2:
    config:
      processes:
        - process_id: 1
          vrfs:
            - vrf: example-vrf
    state: deleted

# Task output:
# commands:
#   - no router ospf 1
```

Using `nxos_ospf_vrf`:
```yaml
# Before state:
# router ospf 1
#   vrf example-vrf

- name: Remove VRF from OSPF process
  cisco.nxos_ospf_vrf:
    ospf: 1
    vrf: example-vrf
    state: absent

# Task output:
# commands:
#   - router ospf 1
#   - no vrf example-vrf
```

**Comment by NilashishC** [comment]
@tpeyton1 Hello! The Resource Modules are focused towards a IaaC (or Source-of-Truth) approach toward config management. The recommended way to leverage these modules is to update the SoT and run the playbook with states  - `overridden` and `replaced` which would then detect the drift in the current device config and the SoT and send updates as required. 

The `state: deleted` will always either remove the specified OSPF processes or when nothing is specified it will remove all OSPF processes in config. It does not support granular deletion. Hence, in your case, if you just removed the `vrfs` entry from the task and use `state:  replaced` (or `overridden`), it would only delete the superfluous VRF. 

For the difference between `replaced` and `overridden` please refer to the examples in the module documentation. For a more generic explanation of these states, you can have a look at this [doc](https://docs.ansible.com/ansible/latest/network/user_guide/network_resource_modules.html#network-resource-module-states).

```yaml
- name: Remove VRF from OSPF process
  cisco.nxos_ospfv2:
    config:
      processes:
        - process_id: 1
    state: replaced
```

Hope that answers your question. Thanks!
