### ISSUE TITLE
Create NX-OS user providing a hashed password

### ISSUE THREAD

**Issue by DavidMorp** [ansible-collections/cisco.nxos#370]
##### SUMMARY
Add the possibility to configure hashed passwords on Cisco NX-OS devices.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
hashed_password

##### ADDITIONAL INFORMATION
Please keep the same syntax as the IOS component: https://docs.ansible.com/ansible/latest/collections/cisco/ios/ios_user_module.html#parameter-hashed_password
```yaml
- name: Add a user with MD5 hashed password
  cisco.ios.ios_user:
    name: ansibletest5
    hashed_password:
      type: 5
      value: $3$8JcDilcYgFZi.yz4ApaqkHG2.8/
```
