### ISSUE TITLE
`cisco.nxos.nxos_telemetry` module does not support `state: gathered`

### ISSUE THREAD

**Issue by cidrblock** [ansible-collections/cisco.nxos#371]
https://github.com/ansible-collections/cisco.nxos/blob/7d82f9abd8258fd64135d2a5ed93c577f1defa71/plugins/modules/nxos_telemetry.py#L196

This causes an issue when using the `ansible.network.resource_manager` role since it is idenified as a resource module but does not support `gathered`

```
- hosts: nxos*
  gather_facts: False
  tasks:
  - include_role:
      name: ansible.network.resource_manager
    vars:
      perform_task: persist
      inventory_directory: ./inventory
      resources:
        - all
```
```
duration: 3.478573
end: '2021-09-29T19:16:14.215960'
event_loop: null
host: nxos101
ignore_errors: null
play: nxos*
play_pattern: nxos*
playbook: /home/bthornto/github/nav_demo/site.yaml
remote_addr: nxos101
res:
  _ansible_no_log: false
  ansible_connection: ansible.netcommon.network_cli
  ansible_network_os: cisco.nxos.nxos
  changed: false
  invocation:
    module_args:
      config: null
      state: gathered
  msg: 'value of state must be one of: merged, replaced, deleted, got: gathered'
  resource_module_name: cisco.nxos.telemetry
role: resource_manager
start: '2021-09-29T19:16:10.737387'
task: Run the platform facts module
task_action: ansible.netcommon.network_resource
task_args: ''
task_path: /home/bthornto/github/nav_demo/collections/ansible_collections/ansible/network/roles/resource_manager/includes/build.yml:2
```
