### ISSUE TITLE
cisco.nxos.nxos_bgp_address_family not supported redistribute hmm

### ISSUE THREAD

**Issue by alexanderdeca** [ansible-collections/cisco.nxos#385]
##### SUMMARY
Using the module it is gathering the existing configuration of the nx-os device, however when redistributing HMM (missing as an option as redistribution protocol) the script stopped as HMM is not a valid redistribution protocol.

- name: CONFIGURE TENANT VRFs UNDER BGP PROCESS
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: "{{ asn }}"
      address_family:
        - afi: "{{ item.afi }}"
          safi: "{{ item.safi }}"
          vrf: "{{ item.vrf }}"
          advertise_l2vpn_evpn: true
  loop: "{{ vrfs }}"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.nxos.nxos_bgp_address_family

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```
adeca@QuAd:~/Devel/ipnexia/nx-os$ ansible --version
ansible [core 2.12.0]
  config file = /Users/adeca/Devel/ipnexia/nx-os/ansible.cfg
  configured module search path = ['/Users/adeca/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/adeca/.virtualenvs/ipnexia/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/adeca/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/adeca/.virtualenvs/ipnexia/bin/ansible
  python version = 3.9.7 (default, Oct 22 2021, 13:39:39) [Clang 13.0.0 (clang-1300.0.29.3)]
  jinja version = 2.11.3
  libyaml = True
```

##### CONFIGURATION

```
HOST_KEY_CHECKING(/Users/adeca/Devel/ipnexia/nx-os/ansible.cfg) = False
```

##### OS / ENVIRONMENT

nx-os 9.3.8

##### STEPS TO REPRODUCE

Trying to add a new l3vni under the bgp address family (IPv4 Unicast) to advertise l2vpn routes host routes, however playbook is stopped because of redistribute hmm (host mobility manager -> redistribute host routes)  which is not supported under the module :

  address-family ipv4 unicast
      advertise l2vpn evpn
      redistribute direct route-map RM-DIRECT
      redistribute **hmm** route-map RM-DIRECT

```
- name: CONFIGURE TENANT VRFs UNDER BGP PROCESS
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: "{{ asn }}"
      address_family:
        - afi: "{{ item.afi }}"
          safi: "{{ item.safi }}"
          vrf: "{{ item.vrf }}"
          advertise_l2vpn_evpn: true
  loop: "{{ vrfs }}"

output when running the playbook :

"msg": "value of protocol must be one of: am, direct, eigrp, isis, lisp, ospf, ospfv3, rip, static, got: hmm found in config -> address_family -> redistribute"
}

```

##### EXPECTED RESULTS

Configuration to be added and not complaining about the value protocol not being supported.

##### ACTUAL RESULTS

playbook is interrupted with the following error msg:

"msg": "value of protocol must be one of: am, direct, eigrp, isis, lisp, ospf, ospfv3, rip, static, got: hmm found in config -> address_family -> redistribute"
}

```
address-family ipv4 unicast
      advertise l2vpn evpn
      redistribute direct route-map RM-DIRECT
      redistribute hmm route-map RM-DIRECT

```

**Comment by alexanderdeca** [comment]
Morning,

Any update on this or how can I help ?

**Comment by NilashishC** [comment]
@alexanderdeca Thank you for raising this ticket. The patch in #404 should fix this issue. However, I noticed that you're using loop in the task. Please note that, the `config` key in this module accepts a list of dictionaries. So you can pass all the AFIs in the same task. For example:

```yaml
- name: Merge the provided configuration with the existing running configuration
  cisco.nxos.nxos_bgp_address_family:
    config:
      as_number: 65536
      address_family:
        - afi: ipv4
          safi: multicast
          networks:
            - prefix: 192.0.2.32/27
            - prefix: 192.0.2.64/27
              route_map: rmap1
          nexthop:
            route_map: rmap2
            trigger_delay:
              critical_delay: 120
              non_critical_delay: 180
        - afi: ipv4
          safi: unicast
          vrf: site-1
          default_information:
            originate: True
          aggregate_address:
            - prefix: 203.0.113.0/24
              as_set: True
              summary_only: True
        - afi: ipv6
          safi: multicast
          vrf: site-1
          redistribute:
            - protocol: ospfv3
              id: 100
              route_map: rmap-ospf-1
            - protocol: eigrp
              id: 101
              route_map: rmap-eigrp-1
```

Looping through AFIs separately will inevitably cause issues with state `replaced` and `overridden`. Please refer to examples in the module documentation on this. Thank you!

https://docs.ansible.com/ansible/latest/collections/cisco/nxos/nxos_bgp_address_family_module.html
