### ISSUE TITLE
key error in parse_structured_interfaces (2.8.1) with nxos 8.4(2c)

### ISSUE THREAD

**Issue by sdx23** [ansible-collections/cisco.nxos#403]
##### SUMMARY
With the collection in version 2.8.1 running against nxos 8.4(2c) switches, fact gathering results in an error:
File \"/tmp/ansible_cisco.nxos.nxos_facts_payload_h_xoky34/ansible_cisco.nxos.nxos_facts_payload.zip/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/facts/legacy/base.py\", line 664, in parse_structured_interfaces\nKeyError: 'interface'\n"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.nxos 2.8.1

##### ANSIBLE VERSION

```paste below
ansible 2.10.16
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansibledeploy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Sep 28 2021, 16:10:42) [GCC 9.3.0]
```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list cisco.nxos

# /home/ansibledeploy/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.nxos 2.8.1  

# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 1.4.0 
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

nxos 8.4(2c)

##### STEPS TO REPRODUCE

Playbook resulting in the error:
```yaml
---
- hosts: ssw-11901
  gather_facts: yes
  vars:
    - ansible_connection: ansible.netcommon.network_cli
    - ansible_user: ansible
    - ansible_become: yes
    - ansible_become_method: enable
    - ansible_network_os: cisco.nxos.nxos

  tasks:
```

Playbook also resulting in the error:
```yaml
---
- hosts: ssw-11901
  gather_facts: no
  vars:
    - ansible_connection: ansible.netcommon.network_cli
    - ansible_user: ansible
    - ansible_become: yes
    - ansible_become_method: enable
    - ansible_network_os: cisco.nxos.nxos

  tasks:
    - name: Gather only the config and default facts
      cisco.nxos.nxos_facts:
        gather_subset:
        - config
        - hardware
        - legacy
        gather_network_resources:
        - interfaces
      register: res
    
    - debug:
       msg: "{{ res }}"
```

Playbook not resulting in the error:
```yaml
---
- hosts: ssw-11901
  gather_facts: no
  vars:
    - ansible_connection: ansible.netcommon.network_cli
    - ansible_user: ansible
    - ansible_become: yes
    - ansible_become_method: enable
    - ansible_network_os: cisco.nxos.nxos

  tasks:
    - name: Gather interfaces resource and minimal legacy facts
      cisco.nxos.nxos_facts:
        gather_subset: min
        gather_network_resources: interfaces
```

##### EXPECTED RESULTS

Expect fact gathering to just work (see playbook three above).

##### ACTUAL RESULTS

Actually fact gathering doesn't work.

```paste below

```
