### ISSUE TITLE
Snmp context instance duplicates output in nxos_snmp_server module

### ISSUE THREAD

**Issue by maugli13** [ansible-collections/cisco.nxos#406]
##### SUMMARY
Attempt to configure snmp-server context fails with instance keyword duplication

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_snmp_server

##### ANSIBLE VERSION

```
ansible 2.10.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
```

##### COLLECTION VERSION

```
# /home/ansible/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.nxos 2.8.2  

# /home/ansible/.local/lib/python3.6/site-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 1.3.1  
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/home/ansible/ansible/hosts']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
```

##### OS / ENVIRONMENT

Ubuntu 18.04.6 LTS

##### STEPS TO REPRODUCE

Run playbook below against any nexus switch

```yaml
- name: "Connections to NXOS switches"
  hosts: nxos
  gather_facts: no

  tasks:
    - name: Add general settings to the configuration
      cisco.nxos.nxos_snmp_server:
        config:
            context:
                instance: test
                name: fcc-prod-tenant1-context
                vrf: FCC-PROD-T01
            mib:
                community_map:
                    community: fcc-prod-tenant1-community
                    context: fcc-prod-tenant1-context
        state: rendered
```

##### EXPECTED RESULTS

Expect to receive the following configuration output:

```
    "rendered": [
        "snmp-server context fcc-prod-tenant1-context instance test vrf FCC-PROD-T01",
        "snmp-server mib community-map fcc-prod-tenant1-community context fcc-prod-tenant1-context"
    ]
```
##### ACTUAL RESULTS

Instead receiving instance keyword duplication

```paste below
    "rendered": [
        "snmp-server context fcc-prod-tenant1-context instance test instance test vrf FCC-PROD-T01",
        "snmp-server mib community-map fcc-prod-tenant1-community context fcc-prod-tenant1-context"
    ]
```
