### ISSUE TITLE
nxos_snmp_server does not create user if localized_key is set.

### ISSUE THREAD

**Issue by tin-ot** [ansible-collections/cisco.nxos#414]
##### SUMMARY

When creating a user with the parameter localized_key the modules returns is correct but nothing is actually configured on the device.

note : not important since localizedV2key is the default value on nxos

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_snmp_server 

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.7] 
```

##### COLLECTION VERSION

```paste below
2.8.2 
```

##### CONFIGURATION

```paste below
con be provided
```

##### OS / ENVIRONMENT

controler:
rhel8
switch:
 cisco Nexus9000 C93180YC-FX 
  System version: 9.2(4)

##### STEPS TO REPRODUCE

```yaml
        - name: SNMP servers conf
          cisco.nxos.nxos_snmp_server:
            config:
              drop:
                unknown_user: true
              users:
                auth:
                  - user: some-user
                    group: some-role
                    authentication:
                      algorithm: sha
                      password: "{{ some_sha_pwd }}"
                      localized_key: true
                      priv:
                        privacy_password: "{{ some_aes_pwd }}"
                        aes_128: true
         #       use_acls:
          #        - user: some-user
           #         ipv4: 1
            state: merged
```

##### EXPECTED RESULTS

    "commands": [
        "snmp-server user some-user some-role auth sha {{ }} priv aes-128 {{ }} localizedkey "

##### ACTUAL RESULTS

no line in config

```paste below

```
