### ISSUE TITLE
snmp_server facts, not gathered if localizedV2key is used

### ISSUE THREAD

**Issue by tin-ot** [ansible-collections/cisco.nxos#415]
##### SUMMARY

Trying to configure snmp user and snmp policy.
The module snmp_server is configuring as expected but unable to gather the configuration for a user if used with localizedV2key.
Thus it will overwrite the user after each execution. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

snmp_server 

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.7] 
```

##### COLLECTION VERSION

```paste below
 2.8.2
```

##### CONFIGURATION

```paste below
not related (can be provided)
```

##### OS / ENVIRONMENT

controller : rhel 8
switch :  System version: 9.3(8) ; HW : Nexus9000 C93180YC-FX 

##### STEPS TO REPRODUCE

create a snmp user and use  localizedV2key 

https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/93x/system-management/b-cisco-nexus-9000-series-nx-os-system-management-configuration-guide-93x/b-cisco-nexus-9000-series-nx-os-system-management-configuration-guide-93x_chapter_01011.html#task_10610021

```yaml
    - name: fact 0.1.0 nxos, gather facts
      cisco.nxos.nxos_facts:
        gather_network_resources:
          - snmp_server
        gather_subset:
          - min
```

##### EXPECTED RESULTS

Facts gathered for this user.

##### ACTUAL RESULTS

User is not gathered.

```paste below

```
