### ISSUE TITLE
nxos_ntp_global use_vrf is not consistent with the NTP data model

### ISSUE THREAD

**Issue by AdamMack2007** [ansible-collections/cisco.nxos#435]
##### SUMMARY
cisco.nxos.nxos_ntp_global does not use the same naming standard for VRF designation as arista.eos.eos_ntp_global and cisco.ios.ios_ntp_global does. 
``` yaml
eos_ntp_global:
  servers:
      - server: test1.com
         vrf: management
      - server: test2.com
         vrf: management
```
This causes the data model to not align for the 3 platforms.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_ntp_global

##### ANSIBLE VERSION
```
any
```

##### COLLECTION VERSION
```
cisco.nxos 2.9.0
```

##### STEPS TO REPRODUCE

``` yaml
- name: Configure NTP
  hosts: all
  vars:
    ntp_config:
      servers:
        - server: test.com
          vrf: management
        - server: test2.com
          vrf: management

  tasks:
    - name: Use NTP resource module [Cisco IOS]
      cisco.ios.ios_ntp_global:
        state: merged
        config: "{{ ntp_config }}"
      when: ansible_network_os == 'ios'

    - name: Use NTP resource module [Cisco NX-OS]
      cisco.nxos.nxos_ntp_global:
        state: merged
        config: "{{ ntp_config }}"
      when: ansible_network_os == 'nxos'
  
    - name: Use NTP resource module [Arista EOS]
      arista.eos.eos_ntp_global:
        state: merged
        config: "{{ ntp_config }}"
      when: ansible_network_os == 'eos'
```

##### EXPECTED RESULTS

Playbook works across EOS, NXOS and IOS.

##### ACTUAL RESULTS
Cisco.Nxos specifies "**use_vrf**" as opposed to "**vrf**" used by Arista.eos and Cisco.ios modules.

Cisco Nexus
``` yaml
ntp_config:
  servers:
    - server: test.com
      use_vrf: management
    - server: test2.com
      use_vrf: management
```
