### ISSUE TITLE
snmp_server user not deleted in state overridden

### ISSUE THREAD

**Issue by tin-ot** [ansible-collections/cisco.nxos#439]
##### SUMMARY

I am trying to remove existing snmp user after a migration.
When using the state overridden, the already configured snmp users are not removed.
If executed directly in the switch CLI, the module's command gives this error:
"Cannot delete the last group of the user"

Note: this issue in not very important. 
I'm using a workaround by reusing the commands in another config module right after in my playbook.
I am just taking the 4 first words of each command: no snmp-server user $USERNAME

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.nxos.nxos_snmp_server

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.2]
  config file = ~/.ansible.cfg
  configured module search path = ['/usr/share/my_modules']
  ansible python module location = /usr/share/ansible/collections
  executable location = .../ansible/.venv/bin/ansible
  python version = 3.8.8 (default, Aug 11 2021, 06:52:42) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
~/.ansible/collections/ansible_collections
Collection Version
---------- -------
```

##### CONFIGURATION

can be parsed.
```paste below

```

##### OS / ENVIRONMENT

controller :
NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"

switch :
  cisco Nexus9000 C93180YC-FX Chassis
  Intel(R) Xeon(R) CPU D-1528 @ 1.90GHz with 24570080 kB of memory.
  Processor Board ID FDO23500AA9

System version: 9.3(8)

##### STEPS TO REPRODUCE

create a valid user with role and credentials

```yaml
- name: nxos override SNMP servers conf
  cisco.nxos.nxos_snmp_server:
    config:
      users:
        auth:
          - user: zabbix-user
            group: zabbix-role
            authentication:
              algorithm: sha
              password: "{{ zabbix_sha_pwd }}"
              priv:
                privacy_password: "{{ zabbix_aes_pwd }}"
                aes_128: true
    state: overridden
```

##### EXPECTED RESULTS

no commands of exiting user actually removing old users.

##### ACTUAL RESULTS

no command being refused by the switch. Users not deleted.

```paste below
no snmp-server user some-user some-role auth sha $ecret priv $secret localizedkey
```
