### ISSUE TITLE
Add a multiline_delimiter for the nxos.banner

### ISSUE THREAD

**Issue by Blackmoresknight** [ansible-collections/cisco.nxos#445]
##### SUMMARY
Add a multiline_delimiter value for the nxos_banner module

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cisco.nxos.nxos_banner

##### ADDITIONAL INFORMATION
In the ios_banner module a multiline_delimiter can be specified. This enables you to change the default multiline_delimiter to something other than an '@'. This way you can add the @ sign to a banner which is useful if it, for example, contains an e-mail address. This functionality does not yet exist in the nxos_banner. The current fixed delimiter is '@' so it's not possible now.

```yaml
- name: configure the exec banner
  cisco.nxos.nxos_banner:
    banner: exec
    text: |
      this is my exec banner
      that contains my email address email@address.com 
      and it's a multiline string
    state: present
```
Will result in the banner:
```yaml
this is my exec banner
```
