### ISSUE TITLE
nxos_logging_global: Ethernet-port-channel facility for state 'replaced' and 'deleted' fails on MDS 

### ISSUE THREAD

**Issue by srbharadwaj** [ansible-collections/cisco.nxos#470]
##### SUMMARY
On MDS switches when we pass `facility: ethernet-port-channel `and `state` as `replaced` or `deleted`, it is sending the wrong cmd to the switch, it sends "`logging level eth_port_channel 0`" when it should actually send "`logging level ethernet-port-channel 0`"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_logging_global

##### ANSIBLE VERSION
latest

##### COLLECTION VERSION
latest

#
##### STEPS TO REPRODUCE

```
  tasks:
        
             - name: facility checking
               cisco.nxos.nxos_logging_global:
                 config:
                    facilities:
                        - facility: ethernet-port-channel
                          severity: emergency
                 state: deleted

```
