### ISSUE TITLE
SNMP community & server with separate lines fails on replaced/overridden

### ISSUE THREAD

**Issue by ledgley** [ansible-collections/cisco.nxos#524]
##### SUMMARY
When using state replaced or overridden, SNMP configuration that appears on two lines results in a failure.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_snmp_server

##### ANSIBLE VERSION
```
ansible [core 2.13.0]
```

##### COLLECTION VERSION
```
(two-ten) edgleyl@LJDX3Q2JV9 compliance % ansible-galaxy collection list | grep nxos
cisco.nxos             3.0.0
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
The device has some existing configuration. Ansible is trying to replace or override it with that provided below.

Simple config
```yaml
snmp:
  communities:
  - name: 3KzJFJiJ2s
    group: network-operator
  - name: 3KzJFJiJ2s
    use_ipv4acl: '99'

  - name: sZfLVQs2as
    group: network-operator
  - name: sZfLVQs2as
    use_ipv4acl: '95'
  contact: 'Luke'
  location: 'Data Centre'
```
Playbook
```yaml
    - name: DEPLOY CONFIG
      cisco.nxos.nxos_snmp_server:
        state: replaced
        config: "{{ iscc.snmp }}"
      register: nxos_snmp_server

    - name: GATHER CONFIG
      cisco.nxos.nxos_snmp_server:
        state: gathered
      register: nxos_snmp_server

    - debug: var=nxos_snmp_server
```
Note - same results with `state: overridden`

Example existing config
```
snmp-server host 10.203.7.13 traps version 2c 3KzJFJiJ2s
snmp-server host 10.203.7.13 use-vrf management
snmp-server community 3KzJFJiJ2s group network-operator
snmp-server community sZfLVQs2as group network-operator
snmp-server community abc123 group network-operator
snmp-server community 3KzJFJiJ2s use-ipv4acl 99
snmp-server community sZfLVQs2as use-ipv4acl 95

##### EXPECTED RESULTS
Ansible should replace the SNMP configuration on the device with that provided.

##### ACTUAL RESULTS
Ansible is trying to remove the `snmp-server host` configuration, which is across two lines on the device. When issuing the command `snmp-server host 10.203.7.13 traps version 2c 3KzJFJiJ2s` this will remove the `use-vrf` line automatically. Then, Ansible tries to remove the `use-vrf` line, resulting in a failure.

This also happens with the communities dictionaries because they too are across two lines.

```
TASK [DEPLOY CONFIG] ***************************************************************************************************************************
fatal: [ausp-fab-ls003]: FAILED! => changed=false
  module_stderr: |-
    no snmp-server host 10.203.7.13 use-vrf management
    host not found
    ausp-fab-ls003(config)#
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
```
