### ISSUE TITLE
[snmp-server] cisco-xcvr-mon-status-chg

### ISSUE THREAD

**Issue by tin-ot** [ansible-collections/cisco.nxos#526]
##### SUMMARY

typo for

snmp-server enable traps link cisco-xcvr-mon-status-chg

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: SNMP servers conf
  cisco.nxos.nxos_snmp_server:
    config:
      traps:
        link:
          cisco_xcvr_mon_status_chg: true
```

##### ACTUAL RESULTS

FAILED - RETRYING: [nce0rtolab01]: snmp 2.0 nxos, override SNMP servers conf (5 retries left).Result was: {
    "attempts": 3,
    "changed": false,
    "module_stderr": "snmp-server enable traps link cisco_xcvr_mon_status_chg\r\r\n                                                    ^\r\n% Invalid command at '^' marker.\r\n\rNCE0RTOLAB01(config)# ",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"

```paste below

```
