### ISSUE TITLE
nxos_command - no explanation of output type 'config'

### ISSUE THREAD

**Issue by stuartgrace-bbc** [ansible-collections/cisco.nxos#538]
##### SUMMARY
When using raw commands which make a change to switch config with NX-API connection, the output type must be set to "config". Without this, the NX-API connection uses a "cli_show_ascii" type which is read-only.

Example: With NX-API connection, this fails because the command type is set to "cli_show_ascii":
```
- name: run command that make a change (FAILS)
  cisco.nxos.nxos_command:
    commands:
    - role name MyRole
```
But it works if the command type is set to "cli_conf" using the output parameter:
```
- name: run command that make a change (SUCCESS)
  cisco.nxos.nxos_command:
    commands:
    - command: role name MyRole
      output: config
```
There is no mention of this in the documentation for nxos_command.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
cisco.nxos.nxos_command

##### ANSIBLE VERSION
```
ansible 2.10.17
  config file = /home/stuartgr/ansible-mist/ansible.cfg
  configured module search path = ['/home/stuartgr/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/stuartgr/ansible-mist/venv/lib/python3.8/site-packages/ansible
  executable location = /home/stuartgr/ansible-mist/venv/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
```
