### ISSUE TITLE
Cannot enable Interface VLAN in NXOS

### ISSUE THREAD

**Issue by oldguardmd** [ansible-collections/cisco.nxos#539]
##### SUMMARY
If you configure a VLAN using nxos_vlan and configure an IP with nxos_l3_interfaces, there appears to be no way to enable the interface VLAN

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Have tried the following:
   nxos_vlans
   nxos_l3_interfaces
   nxos_interfaces

##### ANSIBLE VERSION
```
ansible 2.10.8
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
```

##### COLLECTION VERSION
```
# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 1.4.0
```
##### CONFIGURATION
```
Nothing returned
```

##### OS / ENVIRONMENT
```
Cisco Nexus Operating System (NX-OS) Software
Nexus 9000v is a demo version of the Nexus Operating System

Software
  BIOS: version
  NXOS: version 10.2(1) [Feature Release]
  BIOS compile time:
  NXOS image file is: bootflash:///nxos.10.2.1.F.bin
  NXOS compile time:  8/23/2021 17:00:00 [08/24/2021 02:33:32]

Running in CML 2.2.2

```

##### STEPS TO REPRODUCE
Inventory file example can be found here:
https://github.com/CiscoSE/nxos-ansible-examples/blob/AlittleBroken/MG-Demo/public.inventory.ini

Playbook can be found here:
https://github.com/CiscoSE/nxos-ansible-examples/blob/AlittleBroken/MG-Demo/configDemo.yaml

Task can be found here:
https://github.com/CiscoSE/nxos-ansible-examples/blob/AlittleBroken/MG-Demo/tasks/task-CreateVLANs.yaml

##### EXPECTED RESULTS
Ultimately I think that when I use nxos_l3_interfaces, there should be a switch to set the interface vlan to enabled:
```
- name: Assign IP to VLAN 10 (Core1)
  nxos_l3_interfaces:
    config:
    - name: vlan10
      ipv4:
      - address: 192.168.60.1/25
    state: merged
```
But if the intent is to do all interface shut and no shut operations with **nxos_interfaces**, then that needs to work. And I would suggest providing an example under nxos_vlans that demonstrates how to create the VLAN, assign the IP, and then enable it. This is to common a task to not provide something in the way of clear guidance.

This section of my current code is suspected to be the way to do this based on other issues I reviewed, but it doesn't enable the port and returns no errors.
```
- name: Enable interface VLAN 10 on Core switches
  nxos_interfaces:
    config:
      - name: Vlan10
        enabled: True
  when: (role == "Core") and (ansible_network_os == 'cisco.nxos.nxos')
```

##### ACTUAL RESULTS
Completes successfully, but the interface VLAN remains in a shut state. I have to do a **no shut** from the CLI currently to bring up the interface vlan.
