### ISSUE TITLE
nxos_config replaces > in configs with " "

### ISSUE THREAD

**Issue by Bullenj01** [ansible-collections/cisco.nxos#541]
##### SUMMARY
When using nxos_config to backup running config configuration lists in the format of _src->dst_ cuts out the  _>_ part

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
```

  cisco.nxos.nxos_config:

```

##### ANSIBLE VERSION
ran in ansible tower
```
ansible-playbook 2.9.26
python version = 3.6.8

```

##### COLLECTION VERSION

```
cisco.nxos:3.1.0
```

##### OS / ENVIRONMENT

ansible tower 3.8.4

##### STEPS TO REPRODUCE
create a prefix list named static->eigrp on the device.  After running the job you will see in the output of the var backup that the > has been change to a " "

```yaml
- name: backup nxos config
  cisco.nxos.nxos_config:
    backup: yes
    backup_options:
      dir_path: "{{backup_folder}}"
      filename: "{{ inventory_hostname }}"
    save_when: modified
  connection: ansible.netcommon.httpapi
 register: backup
- name: print backup
  debug:
    msg: "{{ lookup('ansible.builtin.file',backup.backup_path) }}"
```

##### EXPECTED RESULTS
name of prefix list should not be changed in the var

##### ACTUAL RESULTS
this is the relavent output of the print backup task above
```
ip prefix-list static- eigrp seq 5 permit 100.7.19.128/25 \nip prefix-list static- eigrp seq 10 permit 100.24.147.128/25

```
