### ISSUE TITLE
Gather NXOS Feature Status

### ISSUE THREAD

**Issue by ledgley** [ansible-collections/cisco.nxos#547]
##### SUMMARY
It would be useful if `nxos_facts` was able to gather features enabled and disabled on the device.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`cisco.nxos.nxos_facts`

##### ADDITIONAL INFORMATION
Output from `show feature` example
```
switch# show feature
Feature Name          Instance  State
--------------------  --------  --------
Flexlink               1          disabled
analytics              1          enabled
bash-shell             1          disabled
bfd                    1          disabled
bgp                    1          enabled(not-running)
bulkstat               1          disabled
cable-management       1          disabled
catena                 1          disabled
container-tracker      1          disabled
macsec                 1          enabled
```

Might result in something like this

```yaml
ansible_facts:
  net_features:
    - name: Flexlink
      state: disabled
    - name: analytics
      state: enabled
    - name: bash-shell
      state: disabled
    - name: bfd
      state: disabled
    - name: bgp
      state: enabled
```
