### ISSUE TITLE
nxos.snmp_server - using replaced/overridden fails

### ISSUE THREAD

**Issue by chinga-chinga** [ansible-collections/cisco.nxos#554]
##### SUMMARY
When using module nxos_snmp to replace/overidden/delete config as per the example in the collection, the playbook fails with the following error message:

```
fatal: [sw]: FAILED! => {
    "changed": false,
    "module_stderr": ": CLI execution error: Cannot delete the last group of the user\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible-galaxy collection list  cisco.nxos.nxos_snmp_server

##### ANSIBLE VERSION

```
ansible [core 2.13.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxx/venv/ansible/lib64/python3.8/site-packages/ansible
  ansible collection location = /home/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xxx/venv/ansible/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```

cisco.nxos 3.1.0  


```

##### OS / ENVIRONMENT
Software
  NXOS: version 7.0(3)I7(3)
Hardware
  cisco Nexus9000 C93108TC-FX Chassis 

##### STEPS TO REPRODUCE
Used a playbook example layedout in the collection replo for the module

```

- name: Replace snmp-server configurations of listed snmp-server with provided configurations
  cisco.nxos.nxos_snmp_server:
    config:
      aaa_user:
        cache_timeout: 36000
      communities:
        - community: public
          group: network-operator
        - community: secret
          group: network-operator
      contact: nxosswitchadmin2@localhost
      location: serverroom-2
      traps:
        aaa:
          server_state_change: True
      hosts:
        - host: 192.0.2.1
          traps: True
          version: '1'
          community: public
        - host: 192.0.2.1
          source_interface: Ethernet1/1
        - host: 192.0.3.2
          informs: True
          version: '3'
          auth: NMS
      users:
        auth:
          - user: admin
            group: network-admin
            authentication:
              algorithm: md5
              password: "0xcbde46b02c46e0bcd3ac5af6a8b13da9"
              localized_key: True
              priv:
                privacy_password: "0xcbde46b02c46e0bcd3ac5af6a8b13da9"

          - user: snmp_user_1
            group: network-operator
            authentication:
              algorithm: md5
              password: '0x5632724fb8ac3699296af26281e1d0f1'
              localized_key: True

          - user: snmp_user_2
            group: network-operator
            authentication:
              algorithm: md5
              password: '0x5632724fb8ac3699296af26281e1d0f1'
              localized_key: True
              priv:
                privacy_password: '0x5632724fb8ac3699296af26281e1d0f1'
                aes_128: True
        use_acls:
          - user: snmp_user_1
            ipv4: acl1
            ipv6: acl2
    state: replaced


```

The target switch was new with minimaul config and only the default user. I tested with *states overridden, replaced, deleted,* and *merged* all with the same result. 

##### ACTUAL RESULTS

```
fatal: [test-switch]: FAILED! => {
    "changed": false,
    "module_stderr": ": CLI execution error: Cannot delete the last group of the user\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}


```
It looks like this error is returned from the switch, so I can replicate by issuing the same command:

```
sw# show run snmp 

!Command: show running-config snmp
!Time: Tue Sep  6 11:33:24 2022

version 7.0(3)I7(3)
snmp-server contact nxosswitchadmin2@localhost
snmp-server location serverroom-2
snmp-server aaa-user cache-timeout 36000
snmp-server user admin network-admin auth md5 0xcbdsssb02c46e0bcd3ac5af6a8b13da9 priv 0xcbde46b02c46e0bcd3ac5af6a8b13da9 localizedkey
snmp-server user ukadmin network-admin auth md5 0xcbsss6b02c46e0bcd3ac5af6a8b13da9 priv 0xcbde46b02c46e0sss3ac5af6a8b13da9 localizedkey
snmp-server user snmp_user_1 network-operator auth md5 0x5632724fb8ac3699296af26281e1d0f1 localizedkey
snmp-server user snmp_user_3 network-operator auth md5 0x5632724fb8ac3699296af26281e1d0f1 priv aes-128 0x5632724fb8ac3699296af26281e1d0f1 
localizedkey
snmp-server user snmp_user_1 use-ipv4acl acl1 use-ipv6acl acl2
snmp-server host 192.0.2.1 traps version 1 public
snmp-server host 192.0.2.1 source-interface Ethernet1/1
snmp-server host 192.0.3.2 informs version 3 auth NMS
rmon event 1 description FATAL(1) owner PMON@FATAL
rmon event 2 description CRITICAL(2) owner PMON@CRITICAL
rmon event 3 description ERROR(3) owner PMON@ERROR
rmon event 4 description WARNING(4) owner PMON@WARNING
rmon event 5 description INFORMATION(5) owner PMON@INFO
snmp-server enable traps aaa server-state-change


snmp-server community public group network-operator
snmp-server community secret group network-operator


sw# conf t
Enter configuration commands, one per line. End with CNTL/Z.
sw(config)# no snmp-server user ukadmin network-admin auth md5 0xcbde46b02c46e0bcd3ac5af6a8b13da9 priv 0xcbde46b02c46e0bcd3ac5af6a8b13da9 localizedkey
Cannot delete the last group of the user


```
It looks as if ansible is sending a 'no snmp-server user ukadmin network-admin' which the switch is rejecting as it is attempting to remove a group with users still current. 

This is contrary to what is displayed in the collection example.
