### ISSUE TITLE
nxos_vrf: Sub-Interfaces always Report "Changed"

### ISSUE THREAD

**Issue by ashleytayles** [ansible-collections/cisco.nxos#591]
##### SUMMARY

Using nxos_vrf with sub-interfaces always ends up with the task registering as 'changed'. This behaviour does not exist with physical interfaces.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_vrf
##### ANSIBLE VERSION

```paste below
ansible [core 2.12.8]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/e5548197/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/e5548197/ansible2.12_sandbox/.direnv/python-3.8.10/lib/python3.8/site-packages/ansible
  ansible collection location = /home/e5548197/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/e5548197/ansible2.12_sandbox/.direnv/python-3.8.10/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection            Version            
--------------------- -------------------
ansible.netcommon     3.1.0              
ansible.utils         2.6.1              
cisco.mso             2.1.0              
cisco.nxos            3.1.0              
citrix.adc            1.2.0              
community.general     5.7.0              
f5networks.f5_modules 1.18.0             
```

##### CONFIGURATION

```paste below
BLANK
```

##### OS / ENVIRONMENT

Ubuntu 22.04 Ansible Host.
NXOS device: cisco Nexus9000 C93108TC-FX Chassis
  BIOS: version 05.28
  NXOS: version 7.0(3)I7(3)
  BIOS compile time:  01/18/2018
  NXOS image file is: bootflash:///nxos.7.0.3.I7.3.bin
  NXOS compile time:  2/12/2018 13:00:00 [02/12/2018 19:13:48]
 

##### STEPS TO REPRODUCE

```yaml
INVENTORY:

interfaces:

  - name: Ethernet1/30
    vrf: testvrf1
    description: "testvrf1 interface"
    ipv4: 192.168.99.1/30

  - name: Ethernet1/31
    vrf: testvrf2
    description: "testvrf2 interface"
    ipv4: 192.168.100.1/30

  - name: Ethernet1/31.500
    vrf: testvrf2
    description: "testvrf2 interface"
    ipv4: 192.168.100.1/30
    dot1q: 500

  - name: Ethernet1/32
    description: "test non-vrf interface"
    ipv4: 192.168.101.1/30

PLAYBOOK:

- name: 'VRF Interfaces: Add Interfaces to VRF'

  loop: "{{ interfaces }}"
  loop_control:
    loop_var: interface

  when: interface.vrf is defined

  cisco.nxos.nxos_vrf:
    name: "{{ interface.vrf }}"
    interfaces: "{{ interface.name }}"



```

##### EXPECTED RESULTS

This is what happens when Eth1/30 from above inventory is passed over:

```
TASK [nxos_build_vrf : VRF Interfaces: Add Interfaces to VRF] ************************************************************************************************************************************************************************************************************************
ok: [uklab_b_csw01_gen3]
```

##### ACTUAL RESULTS

This is what happens when eth1/31.500 is passed over:

```paste below
TASK [nxos_build_vrf : VRF Interfaces: Add Interfaces to VRF] ************************************************************************************************************************************************************************************************************************
changed: [uklab_b_csw01_gen3]
```

This happens on every run, even if sub-int exists and is still a member of the VRF. Physical ints work as intended.
