### ISSUE TITLE
Utilize the cisco.nxos.nxos_bgp_global  module to create bgp peer-template and apply/inherit the peer-template to bgp neighbors in default and vrf contexts

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.nxos#606]
#### SUMMARY

Utilize the cisco.nxos.nxos_bgp_global  module to create bgp peer-template and apply/inherit the peer-template to bgp neighbors in default and vrf contexts.

##### ISSUE TYPE
- Feature Idea
Currently, these modules are built to add bgp neighbors in global and vrf contexts with required parameters but there is no way to create and apply the neighbor-groups(iosxr) or peer-templates (nxos) with these parameters. This feature is essential as most of our BGP configurations utilize the neighbor-group/peer-template configurations for repeatable and optimal configuration.

##### COMPONENT NAME

cisco.nxos.nxos_bgp_global

##### ADDITIONAL INFORMATION

This would help us avoid adding static templates for neighbor-group configurations and achieve comprehensive bgp configuration within the same module.

```yaml

router bgp {{ template['as_number'] }}
{% for neighbor in template['neighbors'] %}
{% if 'vrf' in neighbor %}
vrf {{ neighbor['vrf'] }}
{% endif %}
neighbor {{ neighbor['neighbor_address'] }}
  use neighbor-group {{ neighbor['neighbor_group'] }}
{% endfor %}


```

**Comment by digitalfiend64** [comment]
My customer has inquired about the status of this issue.  Is there any news or timeframe I can provide back to them?

**Comment by NilashishC** [comment]
@digitalfiend64 We are exploring the best possible way to deal with creation of neighbor templates. However, the ability to use an already existing peer template is current present in the module. As an example,

```yaml
- name: Apply peer-template to BGP neighbor 
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: 65535
      neighbors:
        - neighbor_address: 192.168.1.100 
          description: NBR-1
           inherit:
             peer: nbr_templt
          remote_as: 65563
```
