### ISSUE TITLE
Make the icmpv6 protocol options available for cisco.nxos.nxos_acls like they are for cisco.iosxr.iosxr_acls

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.nxos#624]
##### SUMMARY

Make the icmpv6 protocol options available for cisco.nxos.nxos_acls like they are for cisco.iosxr.iosxr_acls

##### ISSUE TYPE
- Feature Idea
Currently only cisco.iosxr.iosxr.acls module supports icmpv6 and the protocol options.  We have some requests from our customers to use these fields for nxos as well

##### COMPONENT NAME

cisco.nxos.nxos_acls

##### ADDITIONAL INFORMATION

The feature would allow me to use icmp options that are available in the command line for nxos but it does not recognize it in fact gathering or is there away to apply it with the cisco.nxos.nxos.acl module. Below is the nxos example acl ace.
40 permit icmp any any nd-ns 

When that line is added to the acl the fact gathering doesn’t show any protocol options and it can’t be configured in the module.

        -   destination:
                any: true
            grant: permit
            protocol: icmp
            sequence: 30
            source:
                any: true

Below is what the IOSXR config looks like.

```yaml
acls:
        -   acls:
            -   aces:
                -   destination:
                        any: true
                    grant: permit
                    protocol: icmpv6 
                    protocol_options:
                        icmpv6:
                            nd_na: true
                    sequence: 30
                    source:
                        any: true
```
