### ISSUE TITLE
Problem while configuring MDS zoneset

### ISSUE THREAD

**Issue by damalf** [ansible-collections/cisco.nxos#635]
##### SUMMARY
Problem while configuring MDS zoneset

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_zone_zoneset

##### ANSIBLE VERSION

```
          'ansible_version': {'full': '2.13.3',
                              'major': 2,
                              'minor': 13,
                              'revision': 3,
                              'string': '2.13.3'},

```

##### COLLECTION VERSION

```
# /root/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.nxos 4.1.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
            zoneset:
              - name: VSAN23_ZS
                members:
                  - name: GENERALE_ESX
                  - name: GENERALE_PMAX_2427
                action: activate
               

```

##### EXPECTED RESULTS

zoneset created

##### ACTUAL RESULTS

```
fatal: [mdsvsi21]: FAILED! => {"changed": false, "module_stderr": "'dict' object has no attribute 'split'", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"}
[

```
