### ISSUE TITLE
Gathering all facts gives timeout no matter the timeout time.

### ISSUE THREAD

**Issue by aalmenar** [ansible-collections/cisco.nxos#637]
##### SUMMARY
When using a task like:
```yaml
    tasks:
      - name: Gather all facts
        cisco.nxos.nxos_facts:
          gather_subset:
            - all
          gather_network_resources:
            - all
```
Always gives a timeout, no matter if command_timeout is configured to 30 seconds or to 3600 seconds, it only delays the error.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_facts

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.3]
  config file = /ansible-network/ansible.cfg
  configured module search path = ['/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.11/site-packages/ansible
  ansible collection location = /ansible-network/collections
  executable location = /usr/local/bin/ansible
  python version = 3.11.2 (main, Feb 16 2023, 03:07:35) [Clang 14.0.0 (clang-1400.0.29.202)] (/usr/local/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```
Collection Version
---------- -------
cisco.nxos 4.1.0
```

##### OS / ENVIRONMENT
Running: 9.3(10)
Model: Nexus 3048 Chassis
Platform: N3K-C3048TP-1GE

##### STEPS TO REPRODUCE

```yaml
    tasks:
      - name: Gather all facts
        cisco.nxos.nxos_facts:
          gather_subset:
            - all
          gather_network_resources:
            - all
```

##### EXPECTED RESULTS
To retrieve all possible facts from remote equipment.

##### ACTUAL RESULTS

```
TASK [Gather all facts] *********************************************************************************************************************************************
task path: /ansible-network/gather_facts_nxos.yml:8
Loading collection ansible.utils from /ansible-network/collections/ansible_collections/ansible/utils
redirecting (type: terminal) ansible.builtin.nxos to cisco.nxos.nxos
redirecting (type: cliconf) ansible.builtin.nxos to cisco.nxos.nxos
<testswtch.domain> attempting to start connection
<testswtch.domain> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /usr/local/bin/ansible-connection
<testswtch.domain> found existing local domain socket, using it!
<testswtch.domain> invoked shell using ssh_type: libssh
<testswtch.domain> ssh connection done, setting terminal
<testswtch.domain> loaded terminal plugin for network_os nxos
<testswtch.domain> firing event: on_open_shell()
<testswtch.domain> ssh connection has completed successfully
<testswtch.domain> updating play_context for connection
<testswtch.domain>
<testswtch.domain> local domain socket path is /.ansible/pc/50a86a627b
redirecting (type: action) cisco.nxos.nxos_facts to cisco.nxos.nxos
redirecting (type: action) cisco.nxos.nxos_facts to cisco.nxos.nxos
<testswtch.domain> ANSIBLE_NETWORK_IMPORT_MODULES: enabled
<testswtch.domain> ANSIBLE_NETWORK_IMPORT_MODULES: found cisco.nxos.nxos_facts  at /ansible-network/collections/ansible_collections/cisco/nxos/plugins/modules/nxos_facts.py
<testswtch.domain> ANSIBLE_NETWORK_IMPORT_MODULES: running cisco.nxos.nxos_facts
<testswtch.domain> ANSIBLE_NETWORK_IMPORT_MODULES: complete
<testswtch.domain> ANSIBLE_NETWORK_IMPORT_MODULES: Result: {'failed': True, 'msg': 'command timeout triggered, timeout value is 30 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide.', 'exception': '  File "/ansible-network/collections/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py", line 118, in run_commands\n    out = connection.run_commands(commands, check_rc)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__\n    raise ConnectionError(to_text(msg, errors=\'surrogate_then_replace\'), code=code)\n', 'invocation': {'module_args': {'gather_subset': ['all'], 'gather_network_resources': ['all'], 'available_network_resources': False}}, 'warnings': ["** 'feature telemetry' is not enabled. Module will auto-enable feature telemetry ** "], '_ansible_parsed': True}
The full traceback is:
  File "/ansible-network/collections/ansible_collections/cisco/nxos/plugins/module_utils/network/nxos/nxos.py", line 118, in run_commands
    out = connection.run_commands(commands, check_rc)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/ansible/module_utils/connection.py", line 200, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)
[WARNING]: ** 'feature telemetry' is not enabled. Module will auto-enable feature telemetry **
fatal: [testswtch.domain]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "available_network_resources": false,
            "gather_network_resources": [
                "all"
            ],
            "gather_subset": [
                "all"
            ]
        }
    },
    "msg": "command timeout triggered, timeout value is 3600 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."
}

PLAY RECAP *********************************************************************************************************************************************************************
```

**Comment by aalmenar** [comment]
After some debugging, found out that the process does timeout when executing "show interface".

**Comment by NilashishC** [comment]
@aalmenar This is similar to what has been reported in https://github.com/ansible/pylibssh/issues/208. The workaround is to use json-pretty instead of json. For, those Nexus boxes where `| json-pretty` isn't valid, it would fallback to `| json`. But in that case, paramiko has to be used. A similar fix was added in https://github.com/ansible-collections/cisco.nxos/pull/379.

**Comment by NilashishC** [comment]
@aalmenar Could you please test the patch in #650 and let us know if it works for you? Thank you.

**Comment by dwebr** [comment]
> @aalmenar This is similar to what has been reported in [ansible/pylibssh#208](https://github.com/ansible/pylibssh/issues/208). The workaround is to use json-pretty instead of json. For, those Nexus boxes where `| json-pretty` isn't valid, it would fallback to `| json`. But in that case, paramiko has to be used. A similar fix was added in #379.

@NilashishC - The fallback to json does not appear to be working with ansible [core 2.14.0] and cisco.nxos 6.0.0. I have several N7K running version 7.3(7)D1(1) and several N5K that are running 7.3(8)N1(1) where nxos_facts used to work but now fails. 

I'm not sure I follow your comment regarding "But in that case, paramiko has to be used". Could you elaborate on that as maybe that something I need to specify. My virtual environment for ansible7 does have paramiko 2.12.0 installed. I tried setting the environment variable ANSIBLE_NETWORK_CLI_SSH_TYPE=paramiko without any change in the results.

In general we are just seeing zero results for most attributes using the following:
```yaml
- name: Fetch NXOS Facts
  hosts: nxos
  vars_files: 
    - vars/facts_repo_vars.yaml
  vars:
    base_dir: "{{ repo_dir }}/{{ git_repo }}/nxos"
    fact_dir: "{{ base_dir }}/devices"
    run_tags: "{{ ansible_run_tags| default('NONE') }}"
    ansible_ssh_user: "{{ hostvars.localhost.cyberark_result.result.UserName }}"
    ansible_ssh_pass: "{{ hostvars.localhost.cyberark_result.result.Content }}"  
  gather_facts: no
  connection: network_cli

  pre_tasks:
    - name: PRE-FACTS - Before running fact collection, ensure directory for each host is created in "{{ fact_dir }}"
      ansible.builtin.file: path="{{ fact_dir }}/{{ inventory_hostname }}/" state=directory
      tags: always

  tasks:
    - name: NXOS_FACTS - Gather Facts from Device 
      cisco.nxos.nxos_facts:
        gather_subset:
          - '!hardware'
          - '!config'
      vars: 
        ansible_command_timeout: 180
      register: nxos_facts_out
      tags: always
```

Interestingly what tipped me off to this issue was the results we see for ansible_net_fan_info as shown below
```json
{
    "ansible_facts": {
        "ansible_net_all_ipv4_addresses": [],
        "ansible_net_all_ipv6_addresses": [],
        "ansible_net_api": "cliconf",
        "ansible_net_fan_info": [
            {
                "hw_ver": "|",
                "model": "environment",
                "name": "show",
                "status": "json-pretty"
            },
            {
                "hw_ver": "'^'",
                "model": "Invalid",
                "name": "%",
                "status": "marker."
            }
        ],
}
}
```
