### ISSUE TITLE
nxos_bgp_neighbor_address_family module should have field for remote AS number

### ISSUE THREAD

**Issue by CrimsonBinome24** [ansible-collections/cisco.nxos#638]
##### SUMMARY
As bgp needs to know the remote sides AS number to form relationships this module is missing a critical feature for setting up a bgp neighbor. 

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
nxos_bgp_neighbor_address_family

##### ADDITIONAL INFORMATION
`- name: Example with remote as included`
`  cisco.nxos.nxos_bgp_neighbor_address_family:`
`    config:`
`      as_number: 65536`
`      neighbors:`
`        - neighbor_address: 192.0.2.32`
`          remote_as: 64512`
`          address_family:`
`            - afi: ipv4`
`              safi: unicast`
`      vrfs:`
`        - vrf: site-1`
`          neighbors:`
`            - neighbor_address: 203.0.113.1`
`              remote_as: 64513`
`              address_family:`
`                - afi: ipv4`
`                  safi: unicast`

**Comment by NilashishC** [comment]
@CrimsonBinome24 remote_as is not a neighbor address family context option, and as such, it is not a part of the `nxos_neighbor_address_family` module. It has to be configured through the `nxos_bgp_global` module, like below.

```yaml
- name: Merge the provided configuration with the existing running configuration
  cisco.nxos.nxos_bgp_global:
    config:
      as_number: 65563
      neighbors:
        - neighbor_address: 192.168.1.100
          remote_as: 65563
      vrfs:
        - vrf: site-1
          neighbors:
            - neighbor_address: 198.51.100.1
              description: site-1-nbr-1
              remote_as: 65562
```

Hope that helps with your issue.
