### ISSUE TITLE
nxos_lag_interfaces in check mode runs incorrectly when: force is enabled

### ISSUE THREAD

**Issue by from88** [ansible-collections/cisco.nxos#648]
_

##### SUMMARY
Hello, 
nxos_lag_interfaces in check mode runs incorrectly when: force mode is enabled.
When i'm running check mode without force keyword everything is ok. It's also idempotency problem.
I think it's because on the force mode using the checkmode module expects to see **force** word in the interface. But the force mode keyword is not available in running-configuration , you use **force** keyword only when creating the port-channel

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_lag_interfaces

##### ANSIBLE VERSION

```paste below
root@PCEDVKAIL3:/etc/ansible# ansible --version
ansible [core 2.12.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
root@PCEDVKAIL3:/etc/ansible# ansible-galaxy collection list

# /usr/lib/python3/dist-packages/ansible_collections
Collection                    Version
----------------------------- -------
amazon.aws                    2.3.0
ansible.netcommon             2.6.1
ansible.posix                 1.4.0
ansible.utils                 2.6.1
ansible.windows               1.10.0
arista.eos                    3.1.0
awx.awx                       19.4.0
azure.azcollection            1.13.0
check_point.mgmt              2.3.0
chocolatey.chocolatey         1.2.0
cisco.aci                     2.2.0
cisco.asa                     2.1.0
cisco.dnac                    6.5.0
cisco.intersight              1.0.19
cisco.ios                     2.8.1
cisco.iosxr                   2.9.0
cisco.ise                     1.2.1
cisco.meraki                  2.8.0
cisco.mso                     1.4.0
cisco.nso                     1.0.3
cisco.ucs                     1.8.0
cloud.common                  2.1.2
cloudscale_ch.cloud           2.2.2
community.aws                 2.6.1
community.azure               1.1.0
community.ciscosmb            1.0.5
community.crypto              2.3.4
community.digitalocean        1.20.0
community.dns                 2.2.0
community.docker              2.6.0
community.fortios             1.0.0
community.general             4.8.3
community.google              1.0.0
community.grafana             1.5.0
community.hashi_vault         2.5.0
community.hrobot              1.4.0
community.kubernetes          2.0.1
community.kubevirt            1.0.0
community.libvirt             1.1.0
community.mongodb             1.4.1
community.mysql               2.3.8
community.network             3.3.0
community.okd                 2.2.0
community.postgresql          1.7.4
community.proxysql            1.4.0
community.rabbitmq            1.2.1
community.routeros            2.1.0
community.sap                 1.0.0
community.sap_libs            1.1.0
community.skydive             1.0.0
community.sops                1.2.2
community.vmware              1.18.2
community.windows             1.10.0
community.zabbix              1.7.0
containers.podman             1.9.3
cyberark.conjur               1.1.0
cyberark.pas                  1.0.14
dellemc.enterprise_sonic      1.1.1
dellemc.openmanage            4.4.0
dellemc.os10                  1.1.1
dellemc.os6                   1.0.7
dellemc.os9                   1.0.4
f5networks.f5_modules         1.17.0
fortinet.fortimanager         2.1.5
fortinet.fortios              2.1.6
frr.frr                       1.0.4
gluster.gluster               1.0.2
google.cloud                  1.0.2
hetzner.hcloud                1.6.0
hpe.nimble                    1.1.4
ibm.qradar                    1.0.3
infinidat.infinibox           1.3.3
infoblox.nios_modules         1.2.2
inspur.sm                     1.3.0
junipernetworks.junos         2.10.0
kubernetes.core               2.3.2
mellanox.onyx                 1.0.0
netapp.aws                    21.7.0
netapp.azure                  21.10.0
netapp.cloudmanager           21.18.0
netapp.elementsw              21.7.0
netapp.ontap                  21.20.0
netapp.storagegrid            21.10.0
netapp.um_info                21.8.0
netapp_eseries.santricity     1.3.0
netbox.netbox                 3.7.1
ngine_io.cloudstack           2.2.4
ngine_io.exoscale             1.0.0
ngine_io.vultr                1.1.2
openstack.cloud               1.8.0
openvswitch.openvswitch       2.1.0
ovirt.ovirt                   1.6.6
purestorage.flasharray        1.13.0
purestorage.flashblade        1.9.0
sensu.sensu_go                1.13.1
servicenow.servicenow         1.0.6
splunk.es                     1.0.2
t_systems_mms.icinga_director 1.30.0
theforeman.foreman            2.2.0
vmware.vmware_rest            2.2.0
vyos.vyos                     2.8.0
wti.remote                    1.0.4

# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.netcommon 5.0.0
ansible.utils     2.9.0
cisco.nxos        4.1.0
root@PCEDVKAIL3:/etc/ansible#

```

##### CONFIGURATION

```paste below
root@PCEDVKAIL3:/etc/ansible# ansible-config dump --only-changed
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

root@PCEDVKAIL3:/etc/ansible# uname -a
Linux PCEDVKAIL3 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

cisco Nexus9000 C9372PX
  BIOS: version 07.65
  NXOS: version 7.0(3)I7(6)

##### STEPS TO REPRODUCE

    - nxos_lag_interfaces:
        config:
        - name: "{{ port_channel }}"
          members:            
          - member: "{{ interface }}"            
            mode: active
            force: true            
        state: merged

```yaml
- name: TEOLAB interface tests
  hosts: [TEOLAB]
  gather_facts: no
  #check_mode: yes
  strategy: debug
  vars:
    port_channel: port-channel223
    interface: Ethernet1/26
    vlans:
    port_profile_name: test-ansible2
    interface_description: Ansible
  tasks:  
    - name: "Show port-profile brief to see if needed port-profile exists"
      nxos_command:
        commands:
            - "show port-profile brief | include Port-channel"
      register: port_profile_brief
      when: 
        - "port_profile_name != None and vlans == None" 

    - nxos_lag_interfaces:
        config:
        - name: "{{ port_channel }}"
          members:            
          - member: "{{ interface }}"            
            mode: active
            force: true            
        state: merged
      failed_when: "port_profile_name not in port_profile_brief.stdout_lines[0] | map('trim') |  map('split') | map('first')"

    - name: "Show port-channel database to see if {{ port_channel }} exists"
      nxos_command:
        commands:
            - "show port-channel database | include port-channel | exclude Age"
      register: port_channel_database

    - name: "Get port-channel running-configuration if {{ port_channel }} exists"
      nxos_command:
        commands:   
            - "show running-config interface {{ port_channel }}"
      register: portchannel_running_config
      when: "port_channel in port_channel_database.stdout_lines[0] | map('trim') |  map('split') | map('first')"

    - name: "Remove wrong port-profile ({{ portchannel_running_config.stdout[0] | regex_search('inherit port-profile.*') }}) and add the specified one ({{ port_profile_name }})"
      nxos_config:
        lines:
          - shutdown
          - switchport mode trunk
          - "no {{ portchannel_running_config.stdout[0] | regex_search('inherit port-profile.*') }}"
          - inherit port-profile {{port_profile_name}}                        
          - description {{interface_description}}
          - no lacp suspend-individual
          - no shutdown
        parents: "interface {{ port_channel }}"
      register: change_profile
      when: 
        - "portchannel_running_config.stdout_lines[0] is defined and port_profile_name != None and vlans == None" 
        - "portchannel_running_config.stdout_lines[0] is search ('inherit port-profile') and 'inherit port-profile ' ~ port_profile_name not in portchannel_running_config.stdout_lines[0] | map('trim') | list" 

    - name: "Add port-profile ({{port_profile_name}}) to {{ port_channel }}"
      nxos_config:
        lines:
          - shutdown
          - switchport mode trunk
          - inherit port-profile {{port_profile_name}}
          - description {{interface_description}}
          - no lacp suspend-individual
          - no shutdown
        parents: "interface {{ port_channel }}"
      register: add_profile
      when: 
        - "portchannel_running_config.stdout_lines[0] is defined and port_profile_name != None and vlans == None" 
        - "portchannel_running_config.stdout_lines[0] is not search ('inherit port-profile') and change_profile.changed == false"    

    - name: "Check and remove switchport trunk allowed vlan if port-profile is present"
      nxos_config:
        lines:
          - no switchport trunk allowed vlan
        parents: "interface {{ port_channel }}"
      when:  
        - "portchannel_running_config.stdout_lines[0] is defined and port_profile_name != None and vlans == None"
        - "portchannel_running_config.stdout_lines[0] is search ('inherit port-profile') and portchannel_running_config.stdout_lines[0] is search ('switchport trunk allowed vlan')"      

    - name: "Check and remove switchport trunk native vlan if port-profile is present"
      nxos_config:
        lines:
          - no switchport trunk native vlan
        parents: "interface {{ port_channel }}"
      when:  
        - "portchannel_running_config.stdout_lines[0] is defined and port_profile_name != None and vlans == None"
        - "portchannel_running_config.stdout_lines[0] is search ('inherit port-profile') and portchannel_running_config.stdout_lines[0] is search ('switchport trunk native vlan')"    
  
    - name: "Add 'no lacp suspend-individual' if {{ port_channel }} is present and 'no lacp suspend-individual' is missing"      
      nxos_config:
        lines:
        - shutdown
        - no lacp suspend-individual
        - no shutdown
        parents: "interface {{ port_channel }}"
      when: portchannel_running_config.stdout_lines[0] is defined and portchannel_running_config.stdout_lines[0] is not search ('no lacp suspend-individual') and add_profile.changed == false and change_profile.changed == false

    - name: "Add {{port_channel}} description ({{interface_description}}) if there're no description or description is wrong ({{ portchannel_running_config.stdout[0] | regex_search('description.*') }})"
      nxos_config:
        lines:
        - description {{interface_description}}
        parents: "interface {{ port_channel }}"      
      when: portchannel_running_config.stdout_lines[0] is defined and interface_description != None and add_profile.changed == false and change_profile.changed == false and 'description ' ~ interface_description not in portchannel_running_config.stdout_lines[0] | map('trim') | list


```

##### ACTUAL RESULTS

```paste below
from -vvvv output
    "changed": true,
    "commands": [
        "interface Ethernet1/26",
        "channel-group 223 force "
    ],

```
I
