### ISSUE TITLE
Unable to gather all facts from a NXOS device with BGP configuration

### ISSUE THREAD

**Issue by fr-Pursuit** [ansible-collections/cisco.nxos#653]
##### SUMMARY
Whenever I try to use the `cisco.nxos.nxos_facts` task to gather all facts from my NXOS device, it fails with an error. It only happens if any BGP neighbors are configured.

If I also use the `soft-reconfiguration inbound always` directive under a neighbor, a second error is also sometimes randomly thrown instead of the first one.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`nxos_facts`

##### ANSIBLE VERSION
```
ansible [core 2.14.3]
  config file = /home/stendjaoui/network-ansible/ansible.cfg
  configured module search path = ['/home/stendjaoui/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/stendjaoui/.conda/envs/ansible/lib/python3.10/site-packages/ansible
  ansible collection location = /home/stendjaoui/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/stendjaoui/.conda/envs/ansible/bin/ansible
  python version = 3.10.5 | packaged by conda-forge | (main, Jun 14 2022, 07:06:46) [GCC 10.3.0] (/home/stendjaoui/.conda/envs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
# /home/stendjaoui/.conda/envs/ansible/lib/python3.10/site-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 4.1.0
```

##### CONFIGURATION
```
CONFIG_FILE() = /home/stendjaoui/network-ansible/ansible.cfg
DEFAULT_FORKS(/home/stendjaoui/network-ansible/ansible.cfg) = 10
DEFAULT_HASH_BEHAVIOUR(/home/stendjaoui/network-ansible/ansible.cfg) = merge
DEPRECATION_WARNINGS(/home/stendjaoui/network-ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/stendjaoui/network-ansible/ansible.cfg) = True
RETRY_FILES_ENABLED(/home/stendjaoui/network-ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

- The playbook is launched from a Linux host running on RHEL 7.7
- The target host is a Nexus3500 C3548P-10GX running NXOS 9.3(10) with BIOS version 5.6.0

##### STEPS TO REPRODUCE

Use this minimal playbook:

```yaml
---
- name: nxos_facts task test
  hosts: all
  connection: network_cli
  gather_facts: false
  vars:
    ansible_network_cli_ssh_type: paramiko
  tasks:
    - name: Collect all facts from Cisco device
      cisco.nxos.nxos_facts:
        gather_network_resources:
          - all
        gather_subset:
          - all
      register: cisco_facts
```

On a host with this dummy BGP configuration:

```
router bgp 12345
  neighbor 192.168.20.2 remote-as 56789
    address-family ipv4 unicast
      soft-reconfiguration inbound always
```

(remove the last line to consistently get the first error)

##### EXPECTED RESULTS

The task should succeed and register all gathered facts in a variable called `cisco_facts`.

##### ACTUAL RESULTS

The task fails with one of the following two errors:

- [Error 1](https://gist.github.com/fr-Pursuit/78eff163c2ad66afac200fe956da894b)
- [Error 2](https://gist.github.com/fr-Pursuit/922d687f9bcdffb5b030e1f40b002de4)

**Comment by fr-Pursuit** [comment]
After some debugging, I found out that:

- The first error is caused by the `neighbor_address` field not existing in the values of the `neighbors` dictionary (used [here](https://github.com/ansible-collections/cisco.nxos/blob/main/plugins/module_utils/network/nxos/facts/bgp_global/bgp_global.py#L129))
- The second error is caused by the `soft-reconfiguration` directive not being parsed in the context of a neighbor. [This function](https://github.com/ansible-collections/cisco.nxos/blob/main/plugins/module_utils/network/nxos/facts/bgp_neighbor_address_family/bgp_neighbor_address_family.py#L94) is probably at fault here

**Comment by NilashishC** [comment]
@fr-Pursuit This is not reproducible for me with the same configuration you shared. Could you please run the following and see if you're still hitting this issue?

```yaml
---
- name: nxos_facts task test
  hosts: all
  connection: network_cli
  gather_facts: false
  vars:
    ansible_network_cli_ssh_type: paramiko
  tasks:
    - name: Collect all facts from Cisco device
      cisco.nxos.nxos_facts:
        gather_network_resources:
          - bgp_global
          - bgp_address_family
          - bgp_neighbor_address_family
      register: cisco_facts
```
