### ISSUE TITLE
cisco.nxos.nxos_zone_zoneset does not find FC alias to be removed in smart zone

### ISSUE THREAD

**Issue by colinet** [ansible-collections/cisco.nxos#661]
##### SUMMARY
Upon using cisco.nxos.nxos_zone_zoneset to remove FC alias from smart zone, the output states that FC alias provided in plyabook is not in zmart zone. Checking with CLI, the FC alias is in smart zone. The module performs consequently no action.

collection version 4.1.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
 cisco.nxos.nxos_zone_zoneset

##### ANSIBLE VERSION
```
ansible [core 2.11.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/xxxxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.14 (main, Sep 21 2022, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
$ ansible-galaxy collection list | grep nxos
cisco.nxos        4.1.0     <-- manually updated
cisco.nxos                    2.8.2  
$ 
```

##### CONFIGURATION
Standard configuration

##### OS / ENVIRONMENT
OS is RHEL 8.7

##### STEPS TO REPRODUCE
With one fabric, one smart zone and one FC alias, try remove the FC alias from the smart zone.

```
- name: switch_fc | helpers | smartzone update | remove devalias to smartzone
  cisco.nxos.nxos_zone_zoneset:
    zone_zoneset_details:
    - mode: basic
      smart_zoning: true
      vsan: 1000
      zone:
      - members:
        - devtype: initiator
          device_alias: host_fc0
          remove: true
        name: sz_host_fc0
```

##### EXPECTED RESULTS
The module should remove the FC alias from the smart zone.

##### ACTUAL RESULTS
The output exposed state that "zone member 'host_fc0' of device type 'initiator' is not present in zone 'sz_host_fc0' in vsan 1014 hence nothing to remove" which is false. FC lias host_fc0 is in smart zone sz_host_fc0.

```
TASK [ds-role-san_CRUD : switch_fc | helpers | smartzone update | check result] **********************************************************************************************************************************************************
Tuesday 04 April 2023  13:42:03 +0200 (0:00:00.963)       0:00:07.870 ********* 
ok: [localhost] => {
    "_sz_find_output": {
        "changed": false,
        "commands": [],
        "failed": false,
        "messages": [
            "zone mode is already basic ,no change in zone mode configuration for vsan 1000",
            "smart-zoning is already set to enabled , no change in smart-zoning configuration for vsan 1000",
            "zone member 'host_fc0' of device type 'initiator' is not present in zone 'sz_host_fc0' in vsan 1014 hence nothing to remove"
        ]
    }
}
```

**Comment by NilashishC** [comment]
cc @srbharadwaj for MDS issue.

**Comment by colinet** [comment]
Did some more tests about this bug.

Using below playbook, it works: 

```
- name: switch_fc | helpers | smartzone update | remove devalias to smartzone
  cisco.nxos.nxos_zone_zoneset:
    zone_zoneset_details:
    - mode: basic
      smart_zoning: true
      vsan: 1000
      zone:
      - members:
        - devtype: initiator
          pwwn: aa:aa:aa:aa:aa:aa:aa
          # Removal works only with wwpn. Not with devalias
          #device_alias: host_fc0
          remove: true
        name: sz_host_fc0
```

So the issue is that device_alias is not resolved to wwpn.
