### ISSUE TITLE
Update deleted parameter in nxos collection to behave like ios

### ISSUE THREAD

**Issue by digitalfiend64** [ansible-collections/cisco.nxos#666]
Verify first that your feature was not already discussed on GitHub -->

##### SUMMARY

Update deleted parameter in nxos collection to behave like ios.

##### ISSUE TYPE
RFE

##### COMPONENT NAME

cisco.nxos.nxos_static_routes

##### ADDITIONAL INFORMATION

The feature would provide users greater control on which static routes to delete instead of all routes under a specific afi, or vrf.

NXOS
```
cisco.nxos.nxos_static_routes:
- configs:     # static_route module
  - address_families:
    - afi: ipv4
      routes:
      - dest: x.x.x.x/x
        next_hops:
        - admin_distance: 100
          forward_router_address: x.x.x.x
          interface: interface_name
          route_name: vrf_test_static_route
          tag: 4
    vrf: TEST-STATIC-ROUTE-VRF

  - address_families:
    - afi: ipv4
      routes:
      - dest: x.x.x.x/x
        next_hops:
        - admin_distance: 110
          forward_router_address: x.x.x.x
          interface: interface_name
          route_name: ipv4_test_static_route
          tag: 4
        - admin_distance: 120
          forward_router_address: x.x.x.x
          interface: interface_name
          route_name: ipv4_test_static_route
          tag: 4

    - afi: ipv6
      routes:
      - dest: x:x::/x
        next_hops:
        - admin_distance: 130
          dest_vrf: TEST-STATIC-ROUTE-VRF
          forward_router_address: x:x::x
          interface: interface_name
          route_name: ipv6_test_static_route
          tag: 4
  state: deleted
```
