### ISSUE TITLE
Incorrect handling of the "prefer" parameter in the NTP server/peer settings

### ISSUE THREAD

**Issue by rasul-gasanov** [ansible-collections/cisco.nxos#670]
##### SUMMARY
The NTP server/peer preference is always enabled if the "prefer" parameter appears in the server/peer settings, regardless of whether it is set to "True" or "False"

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_ntp_global

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.4]
  python version = 3.9.6 (default, Oct 13 2021, 00:52:10) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3.0.1)] 
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
4.3.0
```

##### STEPS TO REPRODUCE
```yaml
  tasks:
    - name: NTP prefer bug
      cisco.nxos.nxos_ntp_global:
        config:
          servers:
            - server: 10.1.1.1
              prefer: false
          peers:
            - peer: 10.0.0.1
              prefer: false
```

##### EXPECTED RESULTS
ntp peer 10.0.0.1 use-vrf default
ntp server 10.1.1.1 use-vrf default

##### ACTUAL RESULTS
ntp peer 10.0.0.1 prefer use-vrf default
ntp server 10.1.1.1 prefer use-vrf default
```json
{
	"after": {
		"peers": [
			{
				"peer": "10.0.0.1",
				"prefer": true,
				"vrf": "default"
			}
		],
		"servers": [
			{
				"prefer": true,
				"server": "10.1.1.1",
				"vrf": "default"
			}
		]
	},
	"before": {},
	"changed": true,
	"commands": [
		"ntp peer 10.0.0.1 prefer",
		"ntp server 10.1.1.1 prefer"
	]
}
```
