### ISSUE TITLE
Restoring backed up config doesn't apply to interfaces when going from no shutdown -> shutdown

### ISSUE THREAD

**Issue by SereneVirus** [ansible-collections/cisco.nxos#675]
##### SUMMARY

Restoring backup created from cisco.nxos.nxos_config without defaults: true does not shut down interfaces when restoring through cisco.nxos.nxos_config

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cisco.nxos.nxos_config

##### ANSIBLE VERSION

```paste below
ansible [core 2.13.8]
  config file = /home/serene/Elastx/Git/infra/ansible.cfg
  configured module search path = ['/home/serene/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/serene/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/serene/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/serene/.local/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/serene/.local/lib/python3.8/site-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 3.2.0

# /home/serene/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.nxos 4.0.0
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/home/serene/Elastx/Git/infra/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/serene/Elastx/Git/infra/ansible.cfg) = /tmp/.ansible-${USER}/facts-cache
CACHE_PLUGIN_TIMEOUT(/home/serene/Elastx/Git/infra/ansible.cfg) = 3600
CALLBACKS_ENABLED(/home/serene/Elastx/Git/infra/ansible.cfg) = ['ansible.posix.profile_tasks']
DEFAULT_FORKS(/home/serene/Elastx/Git/infra/ansible.cfg) = 20
DEFAULT_HOST_LIST(/home/serene/Elastx/Git/infra/ansible.cfg) = ['/home/serene/Elastx/Git/infra/inventory.py']
DISPLAY_SKIPPED_HOSTS(env: ANSIBLE_DISPLAY_SKIPPED_HOSTS) = False
INTERPRETER_PYTHON(/home/serene/Elastx/Git/infra/ansible.cfg) = auto_silent
```

##### OS / ENVIRONMENT

Hardware
  cisco Nexus9000 C9332D-GX2B Chassis
Software
  BIOS: version 01.10
  NXOS: version 10.2(4) [Maintenance Release]
  Host NXOS: version 10.2(4)  

##### STEPS TO REPRODUCE

Make cisco.nxos.nxos_config restore with intended_config file having:
```
interface Ethernet1/6
  no shutdown

interface Ethernet1/7
  description this-should-be-shutdown

interface Ethernet1/8
  description this-should-also-be-shutdown
```

```yaml
- name: load configuration from file
  cisco.nxos.nxos_config:
    src: "/tmp/{{ config_target }}"
```

##### EXPECTED RESULTS

Config on the device should look like:
```
interface Ethernet1/6
  no shutdown
  
interface Ethernet1/7
  description this-should-be-shutdown

interface Ethernet1/8
  description this-should-also-be-shutdown
```

##### ACTUAL RESULTS

```
interface Ethernet1/6
  no shutdown

interface Ethernet1/7
  description this-should-be-shutdown
  no shutdown

interface Ethernet1/8
  description this-should-also-be-shutdown
  no shutdown
```

If Eth1/7 and Eth1/8 doesn't have descriptions then those will correctly be added by the uploaded config, but it won't shut the interfaces down, which I'm assuming is because there isn't actually a written "shutdown" when downloading the running-config.

```paste below

```

**Comment by SereneVirus** [comment]
After having read the documentation a bit more careful I realized the default config restore mode is "line", meaning each config line is being attempted at the device. Naturally nothing will happen since 'shutdown' is not included.

The workaround was the following (which, again, is included in the documentation):
```
- name: Copy config to device
  cisco.nxos.nxos_file_copy:
    local_file: "/tmp/{{ config_target }}"
    remote_file: "{{ config_target }}"

- name: load configuration from file
  cisco.nxos.nxos_config:
    replace_src: "bootflash:///bootflash:{{ config_target }}"
    replace: config
```
