### ISSUE TITLE
allowed vlan except

### ISSUE THREAD

**Issue by xibriz** [ansible-collections/cisco.nxos#676]
##### SUMMARY
Trying to set the following config:
`switchport trunk allowed vlan except 174-175,189-190`

With the following task:
```
  - name: Nxos Ethernet Interface Exclude vlans
    cisco.nxos.nxos_config:
      lines:
      - switchport trunk allowed vlan except 174-175,189-190
      parents: "interface Ethernet1/25"
```

But the result on the switch is:
`switchport trunk allowed vlan 1-173,176-188,191-4094`

I am unshure if this causes the same behavior on the switch even if the statements seems to be the same.
I tried using the `cisco.nxos.nxos_l2_interfaces` to set the `allowed_vlans` but this gives an error in the `except` keyword.

As I understand it, the `device config parser` mentioned in the docs converts the line, but I can't figure out where and why.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
cisco.nxos.nxos_config
device config parser

##### ANSIBLE VERSION
```
ansible 2.9.6
  config file = /home/ubuntu/automation/edge-network/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
```
