### ISSUE TITLE
nxos_l3_interfaces - add support for interface medium type

### ISSUE THREAD

**Issue by goagex** [ansible-collections/cisco.nxos#696]
##### SUMMARY
Add support for interface medium type (broadcast,p2p)

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
nxos_l3_interfaces

##### ADDITIONAL INFORMATION
```yaml
- name: Merge provided configuration with device configuration.
  cisco.nxos.nxos_l3_interfaces:
    config:
    - name: Ethernet1/1
      ipv4:
      - address: 192.168.1.1/24
      medium: p2p
    state: merged

```
