### ISSUE TITLE
VTP version 3

### ISSUE THREAD

**Issue by jorgenspange** [ansible-collections/cisco.nxos#704]
When using 

````yaml
- name: Configure vtp version
  cisco.nxos.nxos_vtp_version:
    version: 3
````
The play fails with this:
````yaml
fatal: [nexus]: FAILED! => changed=false
  msg: 'value of version must be one of: 1, 2, got: 3'
````

VTP version 3 should be viable in the module.

Would also be nice if the vtp modules were combined so you can set the entire vtp configuration with only one ssh-connection.

Best regards.
