### ISSUE TITLE
Could we get an nxos_interfaces_global module?

### ISSUE THREAD

**Issue by LewisR07** [ansible-collections/cisco.nxos#716]
##### SUMMARY
Is it possible to get an nxos_interfaces_global module like we have for ntp, bgp etc.

It is alot of lines of config to have one module to enable the interface, set MTU and the description, then another todo layer3/layer2 things?

Not sure if its also worth combining the other interface modules (vpc, lacp, hsrp etc.)

Thanks

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

nxos_interfaces module 
nxos_l2_interfaces module
nxos_l3_interfaces module

##### ADDITIONAL INFORMATION

Simplifies the configuration files.

```yaml

- name: Setup interfaces
  cisco.nxos.nxos_interfaces_global:
    config:
    - name: Ethernet1/1
      description: Super Simple L3 Interface configuration
      enabled: true
      mode: access
      vlan: 2501
      ipv4:
        - address: 192.168.25.3/24
    - name: Ethernet1/2
      description: Super Simple Trunk Interface configuration
      enabled: true
      mode: trunk
      allowed_vlans: 2501,2500,1000,888
    state: replaced

```
