### ISSUE TITLE
nxos_bgp_template: evpn safi not allowed

### ISSUE THREAD

**Issue by lowstar** [ansible-collections/cisco.nxos#739]
##### SUMMARY

nxos_bgp_template: `evpn` safi not in the list of allowed choices

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_bgp_template

##### ANSIBLE VERSION

```
ansible [core 2.15.3]
  config file = /Users/xxx/scratch/ansible/ansible.cfg
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/xxx/scratch/ansible/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/xxx/scratch/ansible/venv/bin/ansible
  python version = 3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/xxx/scratch/ansible/venv/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /Users/xxx/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.nxos 5.1.0

# /Users/xxx/scratch/ansible/venv/lib/python3.11/site-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 4.4.0
```

##### CONFIGURATION

```
CONFIG_FILE() = /Users/xxx/scratch/ansible/ansible.cfg
DEFAULT_HOST_LIST(/Users/xxx/scratch/ansible/ansible.cfg) = ['/Users/xxx/scratch/ansible/inventory.yml']
DEPRECATION_WARNINGS(/Users/xxx/scratch/ansible/ansible.cfg) = False
EDITOR(env: EDITOR) = nvim
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

Tested against `NXOS: version 9.3(10)`

##### STEPS TO REPRODUCE

```yaml
- name: BGP peer template
  cisco.nxos.nxos_bgp_templates:
    config:
      as_number: "{{ asn }}"
      neighbor:
        - name: evpn
          remote_as: "{{ asn }}"
          update_source: Loopback0
          address_family:
            - afi: l2vpn
              safi: evpn
              route_reflector_client: True
              send_community:
                both: True
```

##### EXPECTED RESULTS

l2vpn/evpn AFI/SAFI pair should be a valid configuration.

##### ACTUAL RESULTS

```
TASK [spine : BGP peer template] ****************************************************************************************************************************************************
fatal: [spine1]: FAILED! => {"changed": false, "msg": "value of safi must be one of: unicast, multicast, mvpn, got: evpn found in config -> neighbor -> address_family"}
```
