### ISSUE TITLE
nxos_bgp_template: send_community not supported

### ISSUE THREAD

**Issue by lowstar** [ansible-collections/cisco.nxos#740]
##### SUMMARY

nxos_bgp_template: `send_community` not supported

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_bgp_template

##### ANSIBLE VERSION

```
ansible [core 2.15.3]
  config file = /Users/xxx/scratch/ansible/ansible.cfg
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/xxx/scratch/ansible/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/xxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/xxx/scratch/ansible/venv/bin/ansible
  python version = 3.11.5 (main, Aug 24 2023, 15:18:16) [Clang 14.0.3 (clang-1403.0.22.14.1)] (/Users/xxx/scratch/ansible/venv/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
# /Users/xxx/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.nxos 5.1.0

# /Users/xxx/scratch/ansible/venv/lib/python3.11/site-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 4.4.0
```

##### CONFIGURATION

```
CONFIG_FILE() = /Users/xxx/scratch/ansible/ansible.cfg
DEFAULT_HOST_LIST(/Users/xxx/scratch/ansible/ansible.cfg) = ['/Users/xxx/scratch/ansible/inventory.yml']
DEPRECATION_WARNINGS(/Users/xxx/scratch/ansible/ansible.cfg) = False
EDITOR(env: EDITOR) = nvim
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

Tested against `NXOS: version 9.3(10)`

##### STEPS TO REPRODUCE

```yaml
- name: BGP peer template
  cisco.nxos.nxos_bgp_templates:
    config:
      as_number: "{{ asn }}"
      neighbor:
        - name: template
          remote_as: "{{ asn }}"
          update_source: Loopback0
          address_family:
            - afi: ipv4
              safi: unicast
              route_reflector_client: True
              send_community:
                both: True
```

##### EXPECTED RESULTS

`send_community` should be a valid parameter under within address_family parameter (same as in `cisco.nxos.nxos_bgp_neighbor_address_family`)

##### ACTUAL RESULTS

```
TASK [spine : BGP peer template] ****************************************************************************************************************************************************
fatal: [spine1]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (cisco.nxos.nxos_bgp_templates) module: config.neighbor.address_family.send_community. Supported parameters include: advertise_map, advertisement_interval, afi, allowas_in, as_override, capability, default_originate, disable_peer_as_check, filter_list, inherit, maximum_prefix, next_hop_self, next_hop_third_party, prefix_list, route_map, route_reflector_client, safi, soft_reconfiguration_inbound, soo, suppress_inactive, unsuppress_map, weight."}
```
