### ISSUE TITLE
cisco.nxos.nxos_route_maps doesn't support extcommunity rt option

### ISSUE THREAD

**Issue by nimaazizibabani** [ansible-collections/cisco.nxos#743]
##### SUMMARY
cisco.nxos.nxos_route_maps doesn't support extcommunity rt option, it doesn't even capture the command as well.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cisco.nxos.nxos_route_maps

##### ADDITIONAL INFORMATION

This is the config in nxos device

route-map test permit 10
  set extcommunity rt 65000:516587 additive
 
 this is the result in yaml file
         -   action: permit
            sequence: 10
        route_map: test

```yaml

```

**Comment by NilashishC** [comment]
Thank you for opening this ticket!

The following task will be supported once the linked PR is merged.

```yaml
    - cisco.nxos.nxos_route_maps:
        config:
          - route_map: test
             entries:
              - action: permit
                sequence: 10
                set:
                  extcommunity:
                    rt:
                      additive: True
                      extcommunity_numbers:
                        - 65000:516586
                        - 65000:516587
```
