### ISSUE TITLE
Connection type must be fully qualified name for network_cli connection type, got httpapi

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible-collections/cisco.nxos#75]
##### SUMMARY
nxos_file_copy uses connection plugin httpapi, although ```ansible_connection: network_cli``` is explicitly set.
Previous communications with the remote NXOS device in the workflow are made using the httpapi connection plugin.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_file_copy

##### ANSIBLE VERSION
```
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, May 14 2020, 22:08:57) [GCC 9.3.0]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
DEFAULT_EXECUTABLE(/etc/ansible/ansible.cfg) = /bin/bash
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 1000
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_PRIVATE_ROLE_VARS(/etc/ansible/ansible.cfg) = False
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 180
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = ssh
ENABLE_TASK_DEBUGGER(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = True
INTERPRETER_PYTHON(/etc/ansible/ansible.cfg) = /usr/bin/python3
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 3599
PERSISTENT_CONNECT_RETRY_TIMEOUT(/etc/ansible/ansible.cfg) = 200
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 3600
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SHOW_CUSTOM_STATS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
```
controller host: Ubuntu focal 20.04
paramiko : 2.7.1

remote host: NX_OSv_9k 9.2.3
```

##### STEPS TO REPRODUCE
```
# Saving the files in /bootflash by default
- name: Pushing the MTX file "{{ mtx_file }}" 
  vars:
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: 'password'
        ansible_connection: network_cli
        ansible_network_os: nxos
        ansible_password: 'password'
        ansible_user: admin
  nxos_file_copy:
        local_file: "{{ mtx_file }}"
```

##### EXPECTED RESULTS
Successful push

##### ACTUAL RESULTS

```
<172.21.97.178> attempting to start connection
<172.21.97.178> using connection plugin httpapi
<172.21.97.178> found existing local domain socket, using it!
<172.21.97.178> updating play_context for connection
<172.21.97.178> 
<172.21.97.178> local domain socket path is home/user/.ansible/pc/1ea3acc4bd
fatal: [NX_OSv_9k-9.2.3]: FAILED! => {
    "changed": false,
    "msg": "Connection type must be fully qualified name for network_cli connection type, got httpapi"
}
```
