### ISSUE TITLE
Socket is closed error

### ISSUE THREAD

**Issue by ashish-k-panigrahy** [ansible-collections/cisco.nxos#782]
##### SUMMARY
I have been seeing this issue with `nxos_config` module. I don't know what the cause is and how to solve it.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.14.0]
```

##### OS / ENVIRONMENT

CISCO NXOS 9.3(12)

##### STEPS TO REPRODUCE

I am unable to reproduce the issue as this is transient and occurs unexpectedly.

```
- name: Delete IP block 
  nxos_config:
    lines: "no ip prefix-list PLIST-XX1"
    save_when: always
  register: ip_delete_result
  until: ip_delete_result is succeeded
  retries: 3
```

##### EXPECTED RESULTS

Expected it to apply the configurations.

##### ACTUAL RESULTS

Error:
`fatal: [clf01-r03]: FAILED! => {"attempts": 3, "changed": false, "msg": "Socket is closed"}`
