### ISSUE TITLE
bug: invalid configuration not showing failure

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/cisco.nxos#787]
##### SUMMARY
invalid commands do not error with the following task:

```yaml
- name Perform Check Mode Running Config
   cisco.nxos.nxos_config:
     diff_against: intended
     intended_config: "{{ lookup('file', intended_config_path }}"
  register: running_diff
  check_mode: true
  diff: true
```

I have a configuration that is the exact same config on the host BUT I changed the line `hostname test` to `hostvar test`.  The error would show on console if I connect to the device manually and apply.  I also recall it shows for other provider/collections like `arista.eos`, but it does not here.  Instead it shows a output in the std diff presented by ansible of:

```bash
-hostname test
+hostvar test
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
cisco.nxos.nxos_config

##### ANSIBLE VERSION

```paste below
ansible [core 2.16.0]
  config file = None
  configured module search path = ['/Users/rmerolle/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/rmerolle/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.6 (main, Oct  2 2023, 13:45:54) [Clang 15.0.0 (clang-1500.0.40.1)] (/opt/homebrew/opt/python@3.11/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/vscode/.ansible/collections/ansible_collections
Collections Version
----------- -------
cisco.nxos 5.2.1
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Cisco NXOS 10.2(6)

##### STEPS TO REPRODUCE

See summary

##### EXPECTED RESULTS

Task failure pointing out the line with issues similar to arista.eos collection or manually doing this on the cli.

##### ACTUAL RESULTS

See summary
