### ISSUE TITLE
SNMP: Wrong commands for user group and host VRF

### ISSUE THREAD

**Issue by TheRealBecks** [ansible-collections/cisco.nxos#794]
##### SUMMARY

Two commands need to be split into two commands each, so four commands in total.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

nxos_snmp_server

##### ANSIBLE VERSION

```
ansible [core 2.16.1]
  config file = /home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg
  configured module search path = ['/home/mbeckert/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mbeckert/.local/share/virtualenvs/lightning-vg2lOQBb/lib/python3.11/site-packages/ansible
  ansible collection location = /home/mbeckert/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mbeckert/.local/share/virtualenvs/lightning-vg2lOQBb/bin/ansible
  python version = 3.11.6 (main, Nov 15 2023, 09:22:27) [GCC] (/home/mbeckert/.local/share/virtualenvs/lightning-vg2lOQBb/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Current git version
```

##### CONFIGURATION

```
CONFIG_FILE() = /home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg
DEFAULT_FORKS(/home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg) = 10
DEFAULT_HASH_BEHAVIOUR(/home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg) = ['/home/mbeckert/Entwicklung/Strato/lightning/lightning/inventory.yml']
DEFAULT_ROLES_PATH(/home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg) = ['/home/mbeckert/Entwicklung/Strato/lightning/lightning/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/mbeckert/Entwicklung/Strato/lightning/lightning/ansible.cfg) = /home/mbeckert/Entwicklung/Strato/lightning/lightning/.vault_passphrase/open_vault.sh
EDITOR(env: EDITOR) = nano
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

Cisco NXOS 9.3(8)

##### STEPS TO REPRODUCE

```
- name: Test SNMP
  tags:
    - test_snmp
  cisco.nxos.nxos_snmp_server:
    state: "rendered"
    config:
      communities:
        - name: testname1
          group: network-operator
          use_ipv4acl: snmp-ipv4-acl
          use_ipv6acl: snmp-ipv6-acl
      hosts:
        - host: 192.0.2.1
          version: 3
          priv: monitoring
          use_vrf: management
      users:
        auth:
          - user: monitoring
            group: network-operator
            authentication:
              algorithm: sha
              password: authtest1234
              priv:
                aes_128: true
                privacy_password: privtest1234
        use_acls:
          - user: monitoring
            ipv4: snmp-ipv4-acl
            ipv6: snmp-ipv6-acl
```

##### EXPECTED RESULTS

```
snmp-server user monitoring network-operator auth sha authtest1234 priv aes-128 privtest1234
snmp-server user monitoring use-ipv4acl snmp-ipv4-acl use-ipv6acl snmp-ipv6-acl
snmp-server host 192.0.2.1 version 3 priv monitoring
snmp-server host 192.0.2.1 use-vrf management
snmp-server community testname1 group network-operator
snmp-server community testname1 use-ipv4acl snmp-ipv4-acl use-ipv6acl snmp-ipv6-acl
```

##### ACTUAL RESULTS

```
snmp-server user monitoring network-operator auth sha authtest1234 priv aes-128 privtest1234
snmp-server user monitoring use-ipv4acl snmp-ipv4-acl use-ipv6acl snmp-ipv6-acl
snmp-server host 192.0.2.1 use-vrf management version 3 priv monitoring
snmp-server community testname1 group network-operator use-ipv4acl snmp-ipv4-acl use-ipv6acl snmp-ipv6-acl
```
-->
```
sw-cisco-test1(config)# snmp-server host 192.0.2.1 use-vrf management version 3 priv monitoring
                                                                      ^
% Invalid command at '^' marker.
sw-cisco-test1(config)# snmp-server community testname1 group network-operator use-ipv4acl snmp-ipv4-acl use-ipv6acl snmp-ipv6-acl
                                                                               ^
% Invalid command at '^' marker.
```
