### ISSUE TITLE
Allow sshkey to be a list of multiple keys

### ISSUE THREAD

**Issue by opoplawski** [ansible-collections/cisco.nxos#81]
##### SUMMARY
ios_user's sshkey option can be a list of keys.  It is unclear to me if nxos_user accepts this, but it doesn't look like it does.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
nxos_user

##### ADDITIONAL INFORMATION

Ideally one could specify a list of sshkeys for a user:

```yaml
- nxos_user:
    name: testuser
    sshkey:
      - ssh-rsa KEY1
      - ssh-rsa KEY2
```
and it would replace any existing ssh keys with those listed.
