### ISSUE TITLE
ansible_net_neighbors does not report any neighbors

### ISSUE THREAD

**Issue by cpund** [ansible-collections/cisco.nxos#811]
##### SUMMARY
When running a simple playbook to extract all of the facts, using cisco.nxos.facts module (with particular interest in the neighbors), the module silently fails to gather any neighbors, as well as additional weird parsing of some details.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_facts

##### ANSIBLE VERSION
```paste below
ansible [core 2.15.6]
  config file = None
  configured module search path = ['/home/cpund/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cpund/.local/lib/python3.12/site-packages/ansible
  ansible collection location = /home/cpund/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cpund/.local/bin/ansible
  python version = 3.12.0 (main, Oct 21 2023, 17:42:12) [GCC 11.4.0] (/usr/bin/python3.12)
  jinja version = 3.0.3
  libyaml = False
```

##### COLLECTION VERSION
```paste below
# /home/cpund/.ansible/collections/ansible_collections
Collection Version
---------- -------
cisco.nxos 6.0.0

# /home/cpund/.local/lib/python3.12/site-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 4.4.0

# /usr/lib/python3/dist-packages/ansible_collections
Collection Version
---------- -------
cisco.nxos 1.4.0
```

##### CONFIGURATION
```paste below
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

WSL: 5.15.133.1-microsoft-standard-WSL2
Linux flavor: Ubuntu 22.04.3 LTS
Nexus Supervisor: N77-SUP3E
NX-OS Version: 8.3(2)

##### STEPS TO REPRODUCE

```yaml
- name: Save distro facts to a file
  hosts: distro
  gather_facts: false

  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_user: cpund
    ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q REDACTED_BASTION"'
    - name: Extract data
      cisco.nxos.nxos_facts:
        gather_subset:
          - all
          - "!config"
        gather_network_resources:
          - all
      register: result
```

##### EXPECTED RESULTS

I expect for data to be properly extracted and parsed, but have noticed multiple issues with the parsing, particular under the ansible_net_neighbors, ansible_net_fan_info, and ansible_net_interfaces sections.

##### ACTUAL RESULTS
It appears as if the parser is experiencing difficulty in multiple circumstances, as the output indicates that instead of saving the output of the command, it instead saves the command itself. It then tries to parse the saved command (as opposed to the output of it). The Ansible playbook indicates no errors and successfully saves the output to a file as requested later in the playbook. Upon further request, I can work to strip out sensitive information from the -vvvv and post it later.

```paste below
"ansible_net_interfaces": {
    "%": {
        "bandwidth": null,
        "description": null,
        "duplex": null,
        "macaddress": null,
        "mode": null,
        "mtu": null,
        "speed": null,
        "state": null,
        "type": null
    },
    "show": {
        "bandwidth": null,
        "description": null,
        "duplex": null,
        "macaddress": null,
        "mode": null,
        "mtu": null,
        "speed": null,
        "state": null,
        "type": null
    }
},
"ansible_net_fan_info": [
    {
        "hw_ver": "|",
        "model": "environment",
        "name": "show",
        "status": "json-pretty"
    },
    {
        "hw_ver": "'^'",
        "model": "Invalid",
        "name": "%",
        "status": "marker."
    }
],
"ansible_net_neighbors": {},
```
