### ISSUE TITLE
cisco.nxos.nxos_evpn_vni

### ISSUE THREAD

**Issue by heathdbrown** [ansible-collections/cisco.nxos#883]
##### SUMMARY

Running --check when using a playbook leveraging cixo.nxos.nxos_evpn_vni always shows not changed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

- cisco.nxos.nxos_evpn_vni
- https://github.com/ansible-collections/cisco.nxos/blob/main/plugins/modules/nxos_evpn_vni.py#L293

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.2]
  config file = None
  configured module search path = ['/home/omit/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/omit/network_automation/ansible/.venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/omit/.ansible/collections:/usr/share/ansible/collections
  executable location = .venv/bin/ansible
  python version = 3.11.3 (main, Aug 13 2023, 22:42:49) [GCC 11.3.0] (/home/omit/network_automation/ansible/.venv/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection Version
---------- -------
cisco.nxos 9.1.0

```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT

NXOS 9.3.12

##### STEPS TO REPRODUCE

```yaml
ansible-playbook playbook.yaml -i inventory/hosts --check

---
- hosts: all
  connection: network_cli
  gather_facts: false

  tasks:
    - name: Add EVPN VNI
      cisco.nxos.nxos_evpn_vni:
          route_distinguisher: auto
          route_target_import: auto
          route_target_export: auto
          vni: 123456
```

##### EXPECTED RESULTS

When in --check mode when a change needs to be made and the return value has commands the result should show 'changed'.
```
changed: [switch] => "changed: true, "comands": ["evpn", "vni 123456" l2", "rd auto", "route-target import auto", "route-target export auto"]
```

##### ACTUAL RESULTS

```paste below
ok: [switch] => "changed: true, "comands": ["evpn", "vni 123456" l2", "rd auto", "route-target import auto", "route-target export auto"]
```
