### ISSUE TITLE
cisco.nxos.nxos_interfaces module fabric_forwarding_anycast_gateway: true does not work

### ISSUE THREAD

**Issue by Ernestas-S** [ansible-collections/cisco.nxos#887]
##### SUMMARY
`cisco.nxos.nxos_interfaces` module is not configuring the following cli command at all:
`add fabric forwarding mode anycast gateway`

Tested it on 6 different devices, with NX-OS, and then instead had to write our own cli to configure this command:
`
```yaml
    - name: Ensure "ip arp timeout" is configured # add fabric forwarding mode anycast gateway
      cisco.nxos.nxos_config:
        lines: "ip arp timeout 300"
        parents: "interface Vlan9999"
      with_subelements:
<redacted>
      loop_control:
        label: <redacted>

    - name: Ensure "fabric forwarding mode anycast-gateway" is configured
      cisco.nxos.nxos_config:
        lines: 
                - "fabric forwarding mode anycast-gateway"
                - "no shutdown"
        parents: "interface Vlan9999"
      with_subelements:
<redacted>
      loop_control:
        label: <redacted>
```
`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
the awx-ee uses the following collection version: cisco.nxos:9.2.0

##### ANSIBLE VERSION
```paste below
core 2.14.0.dev0
```

##### COLLECTION VERSION
```paste below
cisco.nxos:9.2.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT
The target device output:
            "ansible_net_python_version": "3.8.12",
            "ansible_net_system": "nxos",

##### STEPS TO REPRODUCE

By trying to run the following task

```yaml
    - name: Task that does not work correctly
      cisco.nxos.nxos_interfaces:
        config:
        - name: "Vlan999"
          enabled: true
          description: <redacted>
          mtu: "9999"
          fabric_forwarding_anycast_gateway: true
      with_subelements:
<redacted>
      loop_control:
        label: <redacted>
```

##### EXPECTED RESULTS
I expect that the commands that were send to be executed are executed, as said they are true, however, when checking the nx-os device 'show running config' they are missing:
changed: true
commands:
  - interface Vlan9999
  - description <redacted>
  - no shutdown
  - mtu 9999
  - fabric forwarding mode anycast-gateway

##### ACTUAL RESULTS

The actual configuration is like this in the nx-os device 'show running config':
  - interface Vlan9999
  - description <redacted>
  - mtu 9999
