### ISSUE TITLE
Add peer-switch to nxos_vpc

### ISSUE THREAD

**Issue by sunshinegorgon7** [ansible-collections/cisco.nxos#931]
##### SUMMARY
The current nxos_vpc module support peer_gateway for l3, but doesn't seem to have an option for l2 (peer-switch)

##### COMPONENT NAME
nxos_vpc

##### ADDITIONAL INFORMATION
The idea is to templatize my VPC Configuration across the network w/ Ansible and we are rolling out peer-switch manually due to lack of it in the module, and i can use nxos_config but i don't like that approach.

```
- name: configure
  cisco.nxos.nxos_vpc:
    domain: 100
    role_priority: 32667
    system_priority: 2000
    peer_gw: true
    **peer_sw: true**
    pkl_src: 10.1.100.2
    pkl_dest: 192.168.100.4
    auto_recovery: true

```
