### ISSUE TITLE
Resource Module `nxos_vrf_global` does not have an option for VPN Route Distinguisher (RD)

### ISSUE THREAD

**Issue by Falther1** [ansible-collections/cisco.nxos#935]
##### SUMMARY
It appears that `nxos_vrf_global` is the replacement for `nxos_vrf` but did not get built with a replacement of the `rd` parameter.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
cisco.nxos.nxos_global

##### ADDITIONAL INFORMATION
 In the old module there was an option to specify a [route distinguisher ](https://docs.ansible.com/ansible/latest/collections/cisco/nxos/nxos_vrf_module.html#parameter-aggregate/rd). However in the new resource module this parameter is missing and there doesn't appear to be a replacement option in any other module.

OLD
```yaml
- name: Create VRF
  cisco.nxos.nxos_vrf:
    name: "vrf_name"
    rd: auto
```
